
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalTime;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class CounterStaffScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CounterStaffScreen.class.getName());
    private DataHandler dh = new DataHandler();
    private ExportHandler eh = new ExportHandler();

    /**
     * Creates new form CounterStaffHomescreen
     */
    public CounterStaffScreen() throws IOException {
        initComponents();
        
        tAppointments.getColumnModel().getColumn(5)
            .setCellRenderer(new ButtonRenderer());
        tAppointments.getColumnModel().getColumn(5)
            .setCellEditor(new AppointmentSelectButtonEditor(new JCheckBox(), tAppointments));
        
        tCustomers.getColumnModel().getColumn(4)
            .setCellRenderer(new ButtonRenderer());
        tCustomers.getColumnModel().getColumn(4)
            .setCellEditor(new CustomerUpdateButtonEditor(new JCheckBox(), tCustomers));

        tCustomers.getColumnModel().getColumn(5)
            .setCellRenderer(new ButtonRenderer());
        tCustomers.getColumnModel().getColumn(5)
            .setCellEditor(new CustomerDeleteButtonEditor(new JCheckBox(), tCustomers));
        
        tPayments.getColumnModel().getColumn(5)
            .setCellRenderer(new ButtonRenderer());
        tPayments.getColumnModel().getColumn(5)
            .setCellEditor(new PaymentSelectButtonEditor(new JCheckBox(), tPayments));
        
        onStart();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAppointmentType = new javax.swing.ButtonGroup();
        bExit = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();
        tpTabs = new javax.swing.JTabbedPane();
        pManageAppointments = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAppointments = new javax.swing.JTable();
        tfAppointmentID = new javax.swing.JTextField();
        rbAppointmentTypeNormal = new javax.swing.JRadioButton();
        rbAppointmentTypeMajor = new javax.swing.JRadioButton();
        cbAssignTechnician = new javax.swing.JComboBox<>();
        bAssignAppointment = new javax.swing.JButton();
        lAppointmentID = new javax.swing.JLabel();
        lAppointmentType = new javax.swing.JLabel();
        lAssignTechnician = new javax.swing.JLabel();
        pManageCustomers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCustomers = new javax.swing.JTable();
        tfNewCustomerUsername = new javax.swing.JTextField();
        tfNewCustomerPassword = new javax.swing.JPasswordField();
        tfNewCustomerID = new javax.swing.JTextField();
        tfNewCustomerRole = new javax.swing.JTextField();
        lNewCustomerUsername = new javax.swing.JLabel();
        lNewCustomerPassword = new javax.swing.JLabel();
        lNewCustomerID = new javax.swing.JLabel();
        lNewCustomerRole = new javax.swing.JLabel();
        bCreateUser = new javax.swing.JButton();
        pCollectPayments = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tPayments = new javax.swing.JTable();
        tfPaymentID = new javax.swing.JTextField();
        tfPayAppointmentID = new javax.swing.JTextField();
        lPaymentID = new javax.swing.JLabel();
        lPayAppointmentID = new javax.swing.JLabel();
        lGenerateReceipt = new javax.swing.JLabel();
        bCollectPayment = new javax.swing.JButton();
        bGenerateReceipt = new javax.swing.JButton();
        pProfile = new javax.swing.JPanel();
        tfCurrentID = new javax.swing.JTextField();
        tfCurrentRole = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        tfCurrentPassword = new javax.swing.JPasswordField();
        lID = new javax.swing.JLabel();
        lRole = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lCurrentPassword = new javax.swing.JLabel();
        bUpdateData = new javax.swing.JButton();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bExit.setBackground(new java.awt.Color(255, 51, 51));
        bExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(this::bExitActionPerformed);
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 50));

        lUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        tpTabs.setRequestFocusEnabled(false);

        pManageAppointments.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pManageAppointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Location", "Date", "Time", "Customer Name", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tAppointments);
        if (tAppointments.getColumnModel().getColumnCount() > 0) {
            tAppointments.getColumnModel().getColumn(0).setResizable(false);
            tAppointments.getColumnModel().getColumn(1).setResizable(false);
            tAppointments.getColumnModel().getColumn(2).setResizable(false);
            tAppointments.getColumnModel().getColumn(3).setResizable(false);
            tAppointments.getColumnModel().getColumn(4).setResizable(false);
            tAppointments.getColumnModel().getColumn(5).setResizable(false);
        }

        pManageAppointments.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 670, 260));

        tfAppointmentID.setEditable(false);
        tfAppointmentID.setEnabled(false);
        tfAppointmentID.setFocusable(false);
        tfAppointmentID.setRequestFocusEnabled(false);
        pManageAppointments.add(tfAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 40));

        bgAppointmentType.add(rbAppointmentTypeNormal);
        rbAppointmentTypeNormal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbAppointmentTypeNormal.setText("Normal Service");
        pManageAppointments.add(rbAppointmentTypeNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, -1));

        bgAppointmentType.add(rbAppointmentTypeMajor);
        rbAppointmentTypeMajor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbAppointmentTypeMajor.setText("Major Service");
        pManageAppointments.add(rbAppointmentTypeMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, -1));

        cbAssignTechnician.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pManageAppointments.add(cbAssignTechnician, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, 40));

        bAssignAppointment.setBackground(new java.awt.Color(102, 102, 255));
        bAssignAppointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAssignAppointment.setText("ASSIGN");
        bAssignAppointment.addActionListener(this::bAssignAppointmentActionPerformed);
        pManageAppointments.add(bAssignAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 100, 40));

        lAppointmentID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentID.setText("APPOINTMENT ID");
        pManageAppointments.add(lAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 30));

        lAppointmentType.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentType.setText("APPOINTMENT TYPE");
        pManageAppointments.add(lAppointmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lAssignTechnician.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAssignTechnician.setText("ASSIGN TECHNICIAN");
        pManageAppointments.add(lAssignTechnician, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 140, 30));

        tpTabs.addTab("Manage Appointments", pManageAppointments);

        pManageCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Password", "Role", "Action", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tCustomers);
        if (tCustomers.getColumnModel().getColumnCount() > 0) {
            tCustomers.getColumnModel().getColumn(0).setResizable(false);
            tCustomers.getColumnModel().getColumn(1).setResizable(false);
            tCustomers.getColumnModel().getColumn(2).setResizable(false);
            tCustomers.getColumnModel().getColumn(3).setResizable(false);
            tCustomers.getColumnModel().getColumn(4).setResizable(false);
            tCustomers.getColumnModel().getColumn(5).setResizable(false);
        }

        pManageCustomers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 710, 260));
        pManageCustomers.add(tfNewCustomerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 40));
        pManageCustomers.add(tfNewCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 170, 40));
        pManageCustomers.add(tfNewCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        tfNewCustomerRole.setEditable(false);
        tfNewCustomerRole.setText("CUSTOMER");
        tfNewCustomerRole.setEnabled(false);
        tfNewCustomerRole.setFocusable(false);
        tfNewCustomerRole.setRequestFocusEnabled(false);
        tfNewCustomerRole.setVerifyInputWhenFocusTarget(false);
        pManageCustomers.add(tfNewCustomerRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, 40));

        lNewCustomerUsername.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerUsername.setText("USERNAME");
        pManageCustomers.add(lNewCustomerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 20));

        lNewCustomerPassword.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerPassword.setText("PASSWORD");
        pManageCustomers.add(lNewCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, -1));

        lNewCustomerID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerID.setText("USER ID");
        pManageCustomers.add(lNewCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 20));

        lNewCustomerRole.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerRole.setText("ROLE");
        pManageCustomers.add(lNewCustomerRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        bCreateUser.setBackground(new java.awt.Color(102, 102, 255));
        bCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCreateUser.setText("CREATE USER");
        bCreateUser.addActionListener(this::bCreateUserActionPerformed);
        pManageCustomers.add(bCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 110, 50));

        tpTabs.addTab("Manage Customers", pManageCustomers);

        pCollectPayments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Date", "Amount (RM)", "Appointment ID", "Customer Name", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tPayments);
        if (tPayments.getColumnModel().getColumnCount() > 0) {
            tPayments.getColumnModel().getColumn(0).setResizable(false);
            tPayments.getColumnModel().getColumn(1).setResizable(false);
            tPayments.getColumnModel().getColumn(2).setResizable(false);
            tPayments.getColumnModel().getColumn(3).setResizable(false);
            tPayments.getColumnModel().getColumn(4).setResizable(false);
            tPayments.getColumnModel().getColumn(5).setResizable(false);
        }

        pCollectPayments.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 640, 200));

        tfPaymentID.setEditable(false);
        tfPaymentID.setEnabled(false);
        tfPaymentID.setFocusable(false);
        tfPaymentID.setRequestFocusEnabled(false);
        tfPaymentID.setVerifyInputWhenFocusTarget(false);
        pCollectPayments.add(tfPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 180, 50));

        tfPayAppointmentID.setEditable(false);
        tfPayAppointmentID.setEnabled(false);
        tfPayAppointmentID.setFocusable(false);
        tfPayAppointmentID.setRequestFocusEnabled(false);
        tfPayAppointmentID.setVerifyInputWhenFocusTarget(false);
        pCollectPayments.add(tfPayAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 180, 50));

        lPaymentID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lPaymentID.setText("PAYMENT ID");
        pCollectPayments.add(lPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, 30));

        lPayAppointmentID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lPayAppointmentID.setText("APPOINTMENT ID");
        pCollectPayments.add(lPayAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 130, 30));

        lGenerateReceipt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lGenerateReceipt.setForeground(new java.awt.Color(255, 51, 51));
        lGenerateReceipt.setText("*generate receipt of last collected payment");
        pCollectPayments.add(lGenerateReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 240, 30));

        bCollectPayment.setBackground(new java.awt.Color(102, 102, 255));
        bCollectPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCollectPayment.setText("COLLECT PAYMENT");
        bCollectPayment.addActionListener(this::bCollectPaymentActionPerformed);
        pCollectPayments.add(bCollectPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 150, 60));

        bGenerateReceipt.setBackground(new java.awt.Color(102, 102, 255));
        bGenerateReceipt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bGenerateReceipt.setText("GENERATE RECEIPT");
        bGenerateReceipt.addActionListener(this::bGenerateReceiptActionPerformed);
        pCollectPayments.add(bGenerateReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 150, 60));

        tpTabs.addTab("Collect Payments", pCollectPayments);

        pProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfCurrentID.setEditable(false);
        tfCurrentID.setEnabled(false);
        tfCurrentID.setFocusable(false);
        tfCurrentID.setRequestFocusEnabled(false);
        tfCurrentID.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 41));

        tfCurrentRole.setEditable(false);
        tfCurrentRole.setEnabled(false);
        tfCurrentRole.setFocusable(false);
        tfCurrentRole.setRequestFocusEnabled(false);
        tfCurrentRole.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 190, 41));
        pProfile.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 41));
        pProfile.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 190, 40));
        pProfile.add(tfCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, 30));

        lID.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lID.setText("USER ID");
        pProfile.add(lID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        lRole.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lRole.setText("USER ROLE");
        pProfile.add(lRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 20));

        lUsername.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lUsername.setText("NEW USERNAME");
        pProfile.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        lPassword.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lPassword.setText("NEW PASSWORD");
        lPassword.setToolTipText("");
        pProfile.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 20));

        lCurrentPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCurrentPassword.setText("Enter Current Password");
        pProfile.add(lCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        bUpdateData.setBackground(new java.awt.Color(102, 102, 255));
        bUpdateData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUpdateData.setText("UPDATE DATA");
        bUpdateData.addActionListener(this::bUpdateDataActionPerformed);
        pProfile.add(bUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 130, 50));

        tpTabs.addTab("Profile", pProfile);

        getContentPane().add(tpTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 750, 510));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Counter Staff Screen.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.show();
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateDataActionPerformed
        String newUsername = tfUsername.getText();
        String newPassword = tfPassword.getText();
        String currentPassword = tfCurrentPassword.getText();
        
        try {
            bUpdateData.setEnabled(false);
            User user = loadCurrentUser();
            
            if(currentPassword.equals(user.getPassword())) {
               user.setUsername(newUsername);
               user.setPassword(newPassword);
               
               user.toString();
               
               FileHandler fh = new FileHandler("user.txt");
               fh.updateRecord(tfCurrentID.getText().trim(), user.toString());
               
               FileHandler fh2 = new FileHandler("login.txt");
               fh2.writeLoginUserRecord(user);
               
               JOptionPane.showMessageDialog(null, "Successfully updated User Profile!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
               
               tfUsername.setText(newUsername);
               tfPassword.setText(newPassword);
               tfCurrentPassword.setText("");
               lUser.setText(newUsername);
              
            } else {
                JOptionPane.showMessageDialog(null, "Current Password is Incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
        bUpdateData.setEnabled(true);
        }
    }//GEN-LAST:event_bUpdateDataActionPerformed

    private void bCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateUserActionPerformed
        String newUsername = tfNewCustomerUsername.getText();
        String newPassword = tfNewCustomerPassword.getText();
        String newRole = tfNewCustomerRole.getText();
        String newID = tfNewCustomerID.getText();
        
        FileHandler fh = new FileHandler("user.txt");
        
        User u;
        
        try {
            u = dh.RegisterUser(newID, newUsername, newPassword, newRole);
            if(u == null) return;
            if(!fh.doesRecordExists(u)) {
                fh.writeRecord(u);
                dh.loadUsers();
                JOptionPane.showMessageDialog(null, "User successfully created", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                loadUserTable();   
            } else {
                JOptionPane.showMessageDialog(null, "User already exists!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        tfNewCustomerUsername.setText("");
        tfNewCustomerPassword.setText("");
        tfNewCustomerID.setText("");
        
    }//GEN-LAST:event_bCreateUserActionPerformed

    private void bAssignAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAssignAppointmentActionPerformed
        String appointmentID = tfAppointmentID.getText();
        String appointmentType = "";
        LocalTime appointmentEndTime = null;
        
        FileHandler fh = new FileHandler("appointment.txt");
        
        if (rbAppointmentTypeNormal.isSelected()) {
                appointmentType = "NORMAL";
            } else if (rbAppointmentTypeMajor.isSelected()) {
                appointmentType = "MAJOR";
            }
        
        if (appointmentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select Appointment!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (appointmentType.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select Appointment Type!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            CounterStaff counterStaff = (CounterStaff) loadCurrentUser();
            Appointment appointment = dh.getAppointmentByID(appointmentID);
            
            String technicianUsername = (String) cbAssignTechnician.getSelectedItem();
            
            Technician technician = (Technician) dh.getUserByUsername(technicianUsername);
            
            if (technician == null) {
                JOptionPane.showMessageDialog(null, "Please select a technician!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            appointment.setTechnician(technician);
          
            appointmentEndTime = counterStaff.calculateEndTime(appointmentType, appointment.getAppointmentStartTime());
            
            if(!counterStaff.canAssignTechnician(technician, dh.getAppointments(), dh.getAppointmentCount(), appointment, appointmentEndTime)) {
                JOptionPane.showMessageDialog(null, "Technician is Busy!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            appointment.setAppointmentType(appointmentType);
            appointment.setAppointmentStatus("ASSIGNED");
            appointment.setAppointmentPaymentStatus("UNPAID");
            appointment.setAppointmentEndTime(appointmentEndTime);
            appointment.setCounterStaff(counterStaff);
            
            
            fh.updateRecord(appointmentID, appointment.toString());
            JOptionPane.showMessageDialog(null, "Appointment successfully assigned!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            
            tfAppointmentID.setText("");
            bgAppointmentType.clearSelection();
            
            dh.loadUsers();
            dh.loadAppointments();
            loadAppointmentTable();
            
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
       
        
    }//GEN-LAST:event_bAssignAppointmentActionPerformed

    private void bCollectPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCollectPaymentActionPerformed
        FileHandler fh = new FileHandler("payment.txt");
        FileHandler fh2 = new FileHandler("appointment.txt");
        FileHandler fh3 = new FileHandler("myReceipt.txt");
        
        String paymentID = tfPaymentID.getText();
        String appointmentID = tfPayAppointmentID.getText();
        
        if(paymentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Select Payment!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            CounterStaff counterStaff = (CounterStaff) loadCurrentUser();
            Payment payment = dh.getPaymentByID(paymentID);
            Appointment appointment = dh.getAppointmentByID(appointmentID);
            
            payment.setPaymentStatus("COLLECTED");
            payment.setCounterStaff(counterStaff);
            
            appointment.setAppointmentPaymentStatus("PAID");
            
            fh.updateRecord(paymentID, payment.toString());
            fh2.updateRecord(appointmentID, appointment.toString());
            fh3.overwriteRecord(payment);
            
            dh.loadAppointments();
            dh.loadPayments();     
            loadPaymentTable();
            
            tfPaymentID.setText("");
            tfPayAppointmentID.setText("");
            
            JOptionPane.showMessageDialog(null, "Payment Successfully Collected!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }      
    }//GEN-LAST:event_bCollectPaymentActionPerformed

    private void bGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerateReceiptActionPerformed
        try(BufferedReader br = new BufferedReader(new FileReader("myReceipt.txt"))) {
            
            String line;
            if((line = br.readLine()) != null) {
                String [] record = line.split("\\|");
                
                String paymentID = record[0].trim();
                Payment payment = dh.getPaymentByID(paymentID);
                
                eh.generateReceiptPDF(payment);
                
                JOptionPane.showMessageDialog(null, "Receipt Successfully Generated!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bGenerateReceiptActionPerformed
    
    private User loadCurrentUser() throws FileNotFoundException, IOException {
        String currentUserID = null;
        
        try(BufferedReader br = new BufferedReader(new FileReader("login.txt"))){
            String line = br.readLine();
            
            if(line != null) {
                String [] records = line.split("\\|");
                currentUserID = records [0].trim();      
            }
            
            return dh.getUserByID(currentUserID);
        }
    }
    
    private void loadUserTable() {
        User [] customers = dh.getUserByRole("CUSTOMER");
        
        DefaultTableModel model = (DefaultTableModel) tCustomers.getModel();
        model.setRowCount(0);
        
        for (User u : customers) {
            model.addRow(new Object[]{
                u.getUserID(),
                u.getUsername(),
                u.getPassword(),
                u.getUserRole(),
                "Update",
                "Delete"
            });
        }
    }
    
    private void loadAppointmentTable() throws IOException {
        Appointment [] appointments = dh.getAppointmentByStatus("REQUESTED");
        
        DefaultTableModel model = (DefaultTableModel) tAppointments.getModel();
        model.setRowCount(0);
        
        for (Appointment a : appointments) {
            
            if (a == null) continue;
            
            model.addRow(new Object[] {
                a.getAppointmentID(),
                a.getAppointmentLocation(),
                a.getAppointmentDate(),
                a.getAppointmentStartTime(),
                a.getCustomer().getUsername(),
                "Select"
            });
        }
    }
    
     private void loadPaymentTable() {
        Payment [] payments = dh.getPaymentByStatus("SUBMITTED");
        
        DefaultTableModel model = (DefaultTableModel) tPayments.getModel();
        model.setRowCount(0);
        
        for (Payment p : payments) {
            model.addRow(new Object[]{
                p.getPaymentID(),
                p.getPaymentDate(),
                p.getPaymentAmount(),
                p.getAppointment().getAppointmentID(),
                p.getCustomer().getUsername(),
                "Select"
            });
        }
    }
    
    private void loadTechnicianComboBox() throws IOException {
        
        cbAssignTechnician.removeAllItems();
        
        for (User u : dh.getUserByRole("TECHNICIAN")) {
            cbAssignTechnician.addItem(u.getUsername());
        }
    }
    
    private void onStart() throws FileNotFoundException, IOException{
        
        dh.loadUsers();
        dh.loadAppointments();
        dh.loadFeedback();
        dh.loadPayments();
        User user = loadCurrentUser();
         
        String username = user.getUsername();
        String password = user.getPassword();
        String role = user.getUserRole();
        String id = user.getUserID();
        
        lUser.setText(username);
        tfCurrentID.setText(id);
        tfCurrentRole.setText(role);
        tfUsername.setText(username);
        tfPassword.setText(password);
        loadUserTable();
        loadAppointmentTable();
        loadPaymentTable();
        loadTechnicianComboBox();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CounterStaffScreen().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }
    
    class ButtonRenderer extends JButton implements TableCellRenderer {
        

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "" : value.toString());
            return this;
        }
        
    }
    
    class CustomerDeleteButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");
        private FileHandler fh2 = new FileHandler("appointment.txt");
        private FileHandler fh3 = new FileHandler("feedback.txt");
        
        public CustomerDeleteButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Delete");
            
            button.addActionListener(e -> {
                
                int confirm = JOptionPane.showConfirmDialog(null, "Delete this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                fireEditingStopped();
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                
                Customer customer = (Customer) dh.getUserByID(userID);
                
                try {
                    Appointment [] appointments = dh.getAppointmentByUserID(userID);
                    String[] feedbackIDs = dh.getFeedbackIDsByUserID(userID);
                    String[] appointmentIDs = dh.getAppointmentIDsByUserID(userID);
                    
                    if(customer.hasAssignedAppointment(appointments, appointments.length)) {
                        JOptionPane.showMessageDialog(null, "Cannot delete user. User has assigned appointments!", "ERROR", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    fh3.deleteRecords(feedbackIDs);
                    fh2.deleteRecords(appointmentIDs);
                    fh.deleteRecord(userID);
                    ((DefaultTableModel) table.getModel()).removeRow(row);
                    JOptionPane.showMessageDialog(null, "User successfully deleted", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                  
                    dh.loadUsers();
                    dh.loadAppointments();
                    loadAppointmentTable();
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            });
            
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Delete";
        }
    }
    
    class CustomerUpdateButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");
        
        public CustomerUpdateButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Update");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                int confirm = JOptionPane.showConfirmDialog(null, "Update this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                String username = table.getValueAt(row, 1).toString();
                String password = table.getValueAt(row, 2).toString();
                String role = table.getValueAt(row, 3).toString();
                
                User user = dh.getUserByID(userID);
                
                user.setUsername(username);
                user.setPassword(password);
                
                String newRecord = user.toString();
                
                try {
                    fh.updateRecord(userID, newRecord);
                    JOptionPane.showMessageDialog(null, "User successfully updated", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                    dh.loadUsers();
                    dh.loadAppointments();
                    loadAppointmentTable();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
  
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Update";
        }
    }
    
    class AppointmentSelectButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        
        public AppointmentSelectButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Select");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String appointmentID = table.getValueAt(row, 0).toString(); 
                tfAppointmentID.setText(appointmentID);
            
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Select";
        }
    }
    
    class PaymentSelectButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        
        public PaymentSelectButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Select");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String paymentID = table.getValueAt(row, 0).toString(); 
                String appointmentID = table.getValueAt(row, 3).toString();
                
                tfPaymentID.setText(paymentID);
                tfPayAppointmentID.setText(appointmentID);
            
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Select";
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAssignAppointment;
    private javax.swing.JButton bCollectPayment;
    private javax.swing.JButton bCreateUser;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bGenerateReceipt;
    private javax.swing.JButton bUpdateData;
    private javax.swing.ButtonGroup bgAppointmentType;
    private javax.swing.JComboBox<String> cbAssignTechnician;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lAppointmentID;
    private javax.swing.JLabel lAppointmentType;
    private javax.swing.JLabel lAssignTechnician;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lCurrentPassword;
    private javax.swing.JLabel lGenerateReceipt;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lNewCustomerID;
    private javax.swing.JLabel lNewCustomerPassword;
    private javax.swing.JLabel lNewCustomerRole;
    private javax.swing.JLabel lNewCustomerUsername;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lPayAppointmentID;
    private javax.swing.JLabel lPaymentID;
    private javax.swing.JLabel lRole;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel pCollectPayments;
    private javax.swing.JPanel pManageAppointments;
    private javax.swing.JPanel pManageCustomers;
    private javax.swing.JPanel pProfile;
    private javax.swing.JRadioButton rbAppointmentTypeMajor;
    private javax.swing.JRadioButton rbAppointmentTypeNormal;
    private javax.swing.JTable tAppointments;
    private javax.swing.JTable tCustomers;
    private javax.swing.JTable tPayments;
    private javax.swing.JTextField tfAppointmentID;
    private javax.swing.JTextField tfCurrentID;
    private javax.swing.JPasswordField tfCurrentPassword;
    private javax.swing.JTextField tfCurrentRole;
    private javax.swing.JTextField tfNewCustomerID;
    private javax.swing.JPasswordField tfNewCustomerPassword;
    private javax.swing.JTextField tfNewCustomerRole;
    private javax.swing.JTextField tfNewCustomerUsername;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfPayAppointmentID;
    private javax.swing.JTextField tfPaymentID;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTabbedPane tpTabs;
    // End of variables declaration//GEN-END:variables

}
