
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class CounterStaffScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CounterStaffScreen.class.getName());
    private DataHandler dh = new DataHandler();

    /**
     * Creates new form CounterStaffHomescreen
     */
    public CounterStaffScreen() throws IOException {
        initComponents();
        
        tCustomers.getColumnModel().getColumn(4)
            .setCellRenderer(new ButtonRenderer());
        tCustomers.getColumnModel().getColumn(4)
            .setCellEditor(new UpdateButtonEditor(new JCheckBox(), tCustomers));

        tCustomers.getColumnModel().getColumn(5)
            .setCellRenderer(new ButtonRenderer());
        tCustomers.getColumnModel().getColumn(5)
            .setCellEditor(new DeleteButtonEditor(new JCheckBox(), tCustomers));
        
        onStart();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bExit = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();
        tpTabs = new javax.swing.JTabbedPane();
        pManageAppointments = new javax.swing.JPanel();
        pManageCustomers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCustomers = new javax.swing.JTable();
        tfNewCustomerUsername = new javax.swing.JTextField();
        tfNewCustomerPassword = new javax.swing.JPasswordField();
        tfNewCustomerID = new javax.swing.JTextField();
        tfNewCustomerRole = new javax.swing.JTextField();
        lNewCustomerUsername = new javax.swing.JLabel();
        lNewCustomerPassword = new javax.swing.JLabel();
        lNewCustomerID = new javax.swing.JLabel();
        lNewCustomerRole = new javax.swing.JLabel();
        bCreateUser = new javax.swing.JButton();
        pCollectPayments = new javax.swing.JPanel();
        pProfile = new javax.swing.JPanel();
        tfCurrentID = new javax.swing.JTextField();
        tfCurrentRole = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        tfCurrentPassword = new javax.swing.JPasswordField();
        lID = new javax.swing.JLabel();
        lRole = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lCurrentPassword = new javax.swing.JLabel();
        bUpdateData = new javax.swing.JButton();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bExit.setBackground(new java.awt.Color(255, 51, 51));
        bExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(this::bExitActionPerformed);
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 50));

        lUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        tpTabs.setRequestFocusEnabled(false);

        pManageAppointments.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout pManageAppointmentsLayout = new javax.swing.GroupLayout(pManageAppointments);
        pManageAppointments.setLayout(pManageAppointmentsLayout);
        pManageAppointmentsLayout.setHorizontalGroup(
            pManageAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pManageAppointmentsLayout.setVerticalGroup(
            pManageAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        tpTabs.addTab("Manage Appointments", pManageAppointments);

        pManageCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Password", "Role", "Action", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCustomers.setColumnSelectionAllowed(false);
        jScrollPane1.setViewportView(tCustomers);
        if (tCustomers.getColumnModel().getColumnCount() > 0) {
            tCustomers.getColumnModel().getColumn(0).setResizable(false);
            tCustomers.getColumnModel().getColumn(1).setResizable(false);
            tCustomers.getColumnModel().getColumn(2).setResizable(false);
            tCustomers.getColumnModel().getColumn(3).setResizable(false);
            tCustomers.getColumnModel().getColumn(4).setResizable(false);
            tCustomers.getColumnModel().getColumn(5).setResizable(false);
        }

        pManageCustomers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 710, 260));
        pManageCustomers.add(tfNewCustomerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 40));
        pManageCustomers.add(tfNewCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 170, 40));
        pManageCustomers.add(tfNewCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        tfNewCustomerRole.setEditable(false);
        tfNewCustomerRole.setText("CUSTOMER");
        tfNewCustomerRole.setEnabled(false);
        tfNewCustomerRole.setFocusable(false);
        tfNewCustomerRole.setRequestFocusEnabled(false);
        tfNewCustomerRole.setVerifyInputWhenFocusTarget(false);
        pManageCustomers.add(tfNewCustomerRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, 40));

        lNewCustomerUsername.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerUsername.setText("USERNAME");
        pManageCustomers.add(lNewCustomerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 20));

        lNewCustomerPassword.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerPassword.setText("PASSWORD");
        pManageCustomers.add(lNewCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, -1));

        lNewCustomerID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerID.setText("USER ID");
        pManageCustomers.add(lNewCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 20));

        lNewCustomerRole.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewCustomerRole.setText("ROLE");
        pManageCustomers.add(lNewCustomerRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        bCreateUser.setBackground(new java.awt.Color(102, 102, 255));
        bCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCreateUser.setText("CREATE USER");
        bCreateUser.addActionListener(this::bCreateUserActionPerformed);
        pManageCustomers.add(bCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 110, 50));

        tpTabs.addTab("Manage Customers", pManageCustomers);

        javax.swing.GroupLayout pCollectPaymentsLayout = new javax.swing.GroupLayout(pCollectPayments);
        pCollectPayments.setLayout(pCollectPaymentsLayout);
        pCollectPaymentsLayout.setHorizontalGroup(
            pCollectPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pCollectPaymentsLayout.setVerticalGroup(
            pCollectPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        tpTabs.addTab("Collect Payments", pCollectPayments);

        pProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfCurrentID.setEditable(false);
        tfCurrentID.setEnabled(false);
        tfCurrentID.setFocusable(false);
        tfCurrentID.setRequestFocusEnabled(false);
        tfCurrentID.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 41));

        tfCurrentRole.setEditable(false);
        tfCurrentRole.setEnabled(false);
        tfCurrentRole.setFocusable(false);
        tfCurrentRole.setRequestFocusEnabled(false);
        tfCurrentRole.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 190, 41));
        pProfile.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 41));
        pProfile.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 190, 40));
        pProfile.add(tfCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, 30));

        lID.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lID.setText("USER ID");
        pProfile.add(lID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        lRole.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lRole.setText("USER ROLE");
        pProfile.add(lRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 20));

        lUsername.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lUsername.setText("NEW USERNAME");
        pProfile.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        lPassword.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lPassword.setText("NEW PASSWORD");
        lPassword.setToolTipText("");
        pProfile.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 20));

        lCurrentPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCurrentPassword.setText("Enter Current Password");
        pProfile.add(lCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        bUpdateData.setBackground(new java.awt.Color(102, 102, 255));
        bUpdateData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUpdateData.setText("UPDATE DATA");
        bUpdateData.addActionListener(this::bUpdateDataActionPerformed);
        pProfile.add(bUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 130, 50));

        tpTabs.addTab("Profile", pProfile);

        getContentPane().add(tpTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 750, 510));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Counter Staff Screen.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.show();
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateDataActionPerformed
        String newUsername = tfUsername.getText();
        String newPassword = tfPassword.getText();
        String currentPassword = tfCurrentPassword.getText();
        
        try {
            bUpdateData.setEnabled(false);
            User user = loadUser();
            
            if(currentPassword.equals(user.getPassword())) {
               User u;
               u = new CounterStaff(tfCurrentID.getText(), newUsername, newPassword, tfCurrentRole.getText());
               
               FileHandler fh = new FileHandler("user.txt");
               fh.updateRecord(tfCurrentID.getText().trim(), u.toString());
               
               FileHandler fh2 = new FileHandler("login.txt");
               fh2.writeLoginUserRecord(u);
               
               tfUsername.setText(newUsername);
               tfPassword.setText(newPassword);
               tfCurrentPassword.setText("");
               lUser.setText(newUsername);
              
            } else {
                JOptionPane.showMessageDialog(null, "Current Password is Incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
        bUpdateData.setEnabled(true);
        }
    }//GEN-LAST:event_bUpdateDataActionPerformed

    private void bCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateUserActionPerformed
        String newUsername = tfNewCustomerUsername.getText();
        String newPassword = tfNewCustomerPassword.getText();
        String newRole = tfNewCustomerRole.getText();
        String newID = tfNewCustomerID.getText();
        
        FileHandler fh = new FileHandler("user.txt");
        
        User u;
        
        try {
            u = dh.RegisterUser(newID, newUsername, newPassword, newRole);
            if(!fh.doesRecordExists(u)) {
                fh.writeRecord(u);
                dh.loadUsers();
                JOptionPane.showMessageDialog(null, "User successfully created", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                loadUserTable();   
            } else {
                JOptionPane.showMessageDialog(null, "User already exists!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        tfNewCustomerUsername.setText("");
        tfNewCustomerPassword.setText("");
        tfNewCustomerID.setText("");
        
    }//GEN-LAST:event_bCreateUserActionPerformed
    
    private User loadUser() throws FileNotFoundException, IOException {
        String currentUserID = null;
        
        try(BufferedReader br = new BufferedReader(new FileReader("login.txt"))){
            String line = br.readLine();
            
            if(line != null) {
                String [] records = line.split("\\|");
                currentUserID = records [0].trim();      
            }
            
            return dh.getUserByID(currentUserID);
        }
    }
    
    private void loadUserTable() {
        User [] customers = dh.getUserByRole("CUSTOMER");
        
        DefaultTableModel model = (DefaultTableModel) tCustomers.getModel();
        model.setRowCount(0);
        
        for (User u : customers) {
            model.addRow(new Object[]{
                u.getUserID(),
                u.getUsername(),
                u.getPassword(),
                u.getUserRole(),
                "Update",
                "Delete"
            });
        }
    }
    
    private void onStart() throws FileNotFoundException, IOException{
        
        dh.loadUsers();
        User user = loadUser();
         
        String username = user.getUsername();
        String password = user.getPassword();
        String role = user.getUserRole();
        String id = user.getUserID();
        
        lUser.setText(username);
        tfCurrentID.setText(id);
        tfCurrentRole.setText(role);
        tfUsername.setText(username);
        tfPassword.setText(password);
        loadUserTable();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CounterStaffScreen().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }
    
    class ButtonRenderer extends JButton implements TableCellRenderer {
        

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "" : value.toString());
            return this;
        }
        
    }
    
    class DeleteButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");
        
        public DeleteButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            this.fh = fh;
            
            button = new JButton("Delete");
            
            button.addActionListener(e -> {
                
                int confirm = JOptionPane.showConfirmDialog(null, "Delete this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                fireEditingStopped();
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                
                try {
                    fh.deleteRecord(userID);
                    ((DefaultTableModel) table.getModel()).removeRow(row);
                    JOptionPane.showMessageDialog(null, "User successfully deleted", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            });
            
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Delete";
        }
    }
    
    class UpdateButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");
        
        public UpdateButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            this.fh = fh;
            
            button = new JButton("Update");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                int confirm = JOptionPane.showConfirmDialog(null, "Update this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                String username = table.getValueAt(row, 1).toString();
                String password = table.getValueAt(row, 2).toString();
                String role = table.getValueAt(row, 3).toString();
                
                String newRecord = userID + "|" + username + "|" + password + "|" + role;
                
                try {
                    fh.updateRecord(userID, newRecord);
                    JOptionPane.showMessageDialog(null, "User successfully updated", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
  
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Update";
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreateUser;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bUpdateData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lCurrentPassword;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lNewCustomerID;
    private javax.swing.JLabel lNewCustomerPassword;
    private javax.swing.JLabel lNewCustomerRole;
    private javax.swing.JLabel lNewCustomerUsername;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lRole;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel pCollectPayments;
    private javax.swing.JPanel pManageAppointments;
    private javax.swing.JPanel pManageCustomers;
    private javax.swing.JPanel pProfile;
    private javax.swing.JTable tCustomers;
    private javax.swing.JTextField tfCurrentID;
    private javax.swing.JPasswordField tfCurrentPassword;
    private javax.swing.JTextField tfCurrentRole;
    private javax.swing.JTextField tfNewCustomerID;
    private javax.swing.JPasswordField tfNewCustomerPassword;
    private javax.swing.JTextField tfNewCustomerRole;
    private javax.swing.JTextField tfNewCustomerUsername;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTabbedPane tpTabs;
    // End of variables declaration//GEN-END:variables

}
