
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class CustomerScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerScreen.class.getName());
    private DataHandler dh = new DataHandler();
    private ExportHandler eh = new ExportHandler();

    /**
     * Creates new form CustomerScreen
     */
    public CustomerScreen() throws IOException {
        initComponents();
        jdAppointmentDate.setMinSelectableDate(new Date());
        
        tAppointments.getColumnModel().getColumn(4)
            .setCellRenderer(new ButtonRenderer());
        tAppointments.getColumnModel().getColumn(4)
            .setCellEditor(new AppointmentDeleteButtonEditor(new JCheckBox(), tAppointments));
        
        tPayments.getColumnModel().getColumn(4)
            .setCellRenderer(new ButtonRenderer());
        tPayments.getColumnModel().getColumn(4)
            .setCellEditor(new PayAppointmentSelectButtonEditor(new JCheckBox(), tPayments));
        
        onStart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bExit = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();
        tpTabs = new javax.swing.JTabbedPane();
        pMakeAppointment = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAppointments = new javax.swing.JTable();
        tfAppointmentLocation = new javax.swing.JTextField();
        cbAppointmentStartTime = new javax.swing.JComboBox<>();
        jdAppointmentDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCustomerFeedback = new javax.swing.JTextArea();
        lAppointmentLocation = new javax.swing.JLabel();
        lAppointmentDate = new javax.swing.JLabel();
        lAppointmentStartTime = new javax.swing.JLabel();
        lComments = new javax.swing.JLabel();
        bRequestAppointment = new javax.swing.JButton();
        pMakePayment = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tPayments = new javax.swing.JTable();
        tfPayAppointmentID = new javax.swing.JTextField();
        tfPayAppointmentStartTime = new javax.swing.JTextField();
        tfPayAppointmentEndTime = new javax.swing.JTextField();
        tfPayAppointmentPrice = new javax.swing.JTextField();
        lPayAppointmentID = new javax.swing.JLabel();
        lPayAppointmentStartTime = new javax.swing.JLabel();
        lPayAppointmentEndTime = new javax.swing.JLabel();
        lPayAppointmentPrice = new javax.swing.JLabel();
        bPay = new javax.swing.JButton();
        pViewFeedback = new javax.swing.JPanel();
        pHistory = new javax.swing.JPanel();
        pProfile = new javax.swing.JPanel();
        tfCurrentID = new javax.swing.JTextField();
        tfCurrentRole = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        tfCurrentPassword = new javax.swing.JPasswordField();
        lID = new javax.swing.JLabel();
        lRole = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lCurrentPassword = new javax.swing.JLabel();
        bUpdateData = new javax.swing.JButton();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bExit.setBackground(new java.awt.Color(255, 51, 51));
        bExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(this::bExitActionPerformed);
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 50));

        lUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        pMakeAppointment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Location", "Date", "Start Time", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tAppointments);
        if (tAppointments.getColumnModel().getColumnCount() > 0) {
            tAppointments.getColumnModel().getColumn(0).setResizable(false);
            tAppointments.getColumnModel().getColumn(1).setResizable(false);
            tAppointments.getColumnModel().getColumn(2).setResizable(false);
            tAppointments.getColumnModel().getColumn(3).setResizable(false);
            tAppointments.getColumnModel().getColumn(4).setResizable(false);
        }

        pMakeAppointment.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 660, 200));
        pMakeAppointment.add(tfAppointmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 40));

        cbAppointmentStartTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:00", "16:00", "16:30" }));
        pMakeAppointment.add(cbAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, 40));
        pMakeAppointment.add(jdAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 190, 40));

        taCustomerFeedback.setColumns(20);
        taCustomerFeedback.setRows(5);
        jScrollPane2.setViewportView(taCustomerFeedback);

        pMakeAppointment.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 90));

        lAppointmentLocation.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentLocation.setText("APPOINTMENT LOCATION");
        pMakeAppointment.add(lAppointmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 200, 30));

        lAppointmentDate.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentDate.setText("APPOINTMENT DATE");
        pMakeAppointment.add(lAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 160, 30));

        lAppointmentStartTime.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentStartTime.setText("APPOINTMENT START TIME");
        pMakeAppointment.add(lAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 220, 30));

        lComments.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lComments.setText("COMMENTS");
        pMakeAppointment.add(lComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 170, 30));

        bRequestAppointment.setBackground(new java.awt.Color(255, 153, 51));
        bRequestAppointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bRequestAppointment.setText("REQUEST");
        bRequestAppointment.addActionListener(this::bRequestAppointmentActionPerformed);
        pMakeAppointment.add(bRequestAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 130, 50));

        tpTabs.addTab("Make Appointment", pMakeAppointment);

        pMakePayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Date", "Appointment Type", "Location", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tPayments);
        if (tPayments.getColumnModel().getColumnCount() > 0) {
            tPayments.getColumnModel().getColumn(0).setResizable(false);
            tPayments.getColumnModel().getColumn(1).setResizable(false);
            tPayments.getColumnModel().getColumn(2).setResizable(false);
            tPayments.getColumnModel().getColumn(3).setResizable(false);
            tPayments.getColumnModel().getColumn(4).setResizable(false);
        }

        pMakePayment.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 670, 180));

        tfPayAppointmentID.setEditable(false);
        tfPayAppointmentID.setEnabled(false);
        tfPayAppointmentID.setFocusable(false);
        tfPayAppointmentID.setRequestFocusEnabled(false);
        tfPayAppointmentID.setVerifyInputWhenFocusTarget(false);
        pMakePayment.add(tfPayAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 50));

        tfPayAppointmentStartTime.setEditable(false);
        tfPayAppointmentStartTime.setEnabled(false);
        tfPayAppointmentStartTime.setFocusable(false);
        tfPayAppointmentStartTime.setRequestFocusEnabled(false);
        tfPayAppointmentStartTime.setVerifyInputWhenFocusTarget(false);
        pMakePayment.add(tfPayAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 200, 50));

        tfPayAppointmentEndTime.setEditable(false);
        tfPayAppointmentEndTime.setEnabled(false);
        tfPayAppointmentEndTime.setFocusable(false);
        tfPayAppointmentEndTime.setRequestFocusEnabled(false);
        tfPayAppointmentEndTime.setVerifyInputWhenFocusTarget(false);
        pMakePayment.add(tfPayAppointmentEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 200, 50));

        tfPayAppointmentPrice.setEditable(false);
        tfPayAppointmentPrice.setEnabled(false);
        tfPayAppointmentPrice.setFocusable(false);
        tfPayAppointmentPrice.setRequestFocusEnabled(false);
        tfPayAppointmentPrice.setVerifyInputWhenFocusTarget(false);
        pMakePayment.add(tfPayAppointmentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 50));

        lPayAppointmentID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lPayAppointmentID.setText("APPOINTMENT ID");
        pMakePayment.add(lPayAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 30));

        lPayAppointmentStartTime.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lPayAppointmentStartTime.setText("APPOINTMENT START TIME");
        pMakePayment.add(lPayAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, 30));

        lPayAppointmentEndTime.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lPayAppointmentEndTime.setText("APPOINTMENT END TIME");
        pMakePayment.add(lPayAppointmentEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 190, 30));

        lPayAppointmentPrice.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lPayAppointmentPrice.setText("PRICE (RM)");
        pMakePayment.add(lPayAppointmentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 40));

        bPay.setBackground(new java.awt.Color(255, 153, 51));
        bPay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bPay.setText("PAY");
        bPay.addActionListener(this::bPayActionPerformed);
        pMakePayment.add(bPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 140, 50));

        tpTabs.addTab("Make Payment", pMakePayment);

        javax.swing.GroupLayout pViewFeedbackLayout = new javax.swing.GroupLayout(pViewFeedback);
        pViewFeedback.setLayout(pViewFeedbackLayout);
        pViewFeedbackLayout.setHorizontalGroup(
            pViewFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pViewFeedbackLayout.setVerticalGroup(
            pViewFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tpTabs.addTab("View Feedback", pViewFeedback);

        javax.swing.GroupLayout pHistoryLayout = new javax.swing.GroupLayout(pHistory);
        pHistory.setLayout(pHistoryLayout);
        pHistoryLayout.setHorizontalGroup(
            pHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pHistoryLayout.setVerticalGroup(
            pHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tpTabs.addTab("History", pHistory);

        pProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfCurrentID.setEditable(false);
        tfCurrentID.setEnabled(false);
        tfCurrentID.setFocusable(false);
        tfCurrentID.setRequestFocusEnabled(false);
        tfCurrentID.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 41));

        tfCurrentRole.setEditable(false);
        tfCurrentRole.setEnabled(false);
        tfCurrentRole.setFocusable(false);
        tfCurrentRole.setRequestFocusEnabled(false);
        tfCurrentRole.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 190, 41));
        pProfile.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 41));
        pProfile.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 190, 40));
        pProfile.add(tfCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, 30));

        lID.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lID.setText("USER ID");
        pProfile.add(lID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        lRole.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lRole.setText("USER ROLE");
        pProfile.add(lRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 20));

        lUsername.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lUsername.setText("NEW USERNAME");
        pProfile.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        lPassword.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lPassword.setText("NEW PASSWORD");
        lPassword.setToolTipText("");
        pProfile.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 20));

        lCurrentPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCurrentPassword.setText("Enter Current Password");
        pProfile.add(lCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        bUpdateData.setBackground(new java.awt.Color(255, 153, 51));
        bUpdateData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUpdateData.setText("UPDATE DATA");
        bUpdateData.addActionListener(this::bUpdateDataActionPerformed);
        pProfile.add(bUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 130, 50));

        tpTabs.addTab("Profile", pProfile);

        getContentPane().add(tpTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 740, 500));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Customer Screen.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.show();
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateDataActionPerformed
        String newUsername = tfUsername.getText();
        String newPassword = tfPassword.getText();
        String currentPassword = tfCurrentPassword.getText();

        try {
            bUpdateData.setEnabled(false);
            User user = loadCurrentUser();

            if(currentPassword.equals(user.getPassword())) {
                user.setUsername(newUsername);
                user.setPassword(newPassword);

                user.toString();

                FileHandler fh = new FileHandler("user.txt");
                fh.updateRecord(tfCurrentID.getText().trim(), user.toString());

                FileHandler fh2 = new FileHandler("login.txt");
                fh2.writeLoginUserRecord(user);
                
                FileHandler fh3 = new FileHandler("auditLog.txt");
                AuditLog.log(fh3, fh3.generateNextID("AD"), user.getUserID(), "UPDATE", user.getUserID(), "UPDATE USER DETAILS");

                JOptionPane.showMessageDialog(null, "Successfully updated User Profile!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);

                tfUsername.setText(newUsername);
                tfPassword.setText(newPassword);
                tfCurrentPassword.setText("");
                lUser.setText(newUsername);

            } else {
                JOptionPane.showMessageDialog(null, "Current Password is Incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
            bUpdateData.setEnabled(true);
        }
    }//GEN-LAST:event_bUpdateDataActionPerformed

    private void bRequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRequestAppointmentActionPerformed
        FileHandler fh = new FileHandler("appointment.txt");
        FileHandler fh2 = new FileHandler("feedback.txt");
        FileHandler fh3 = new FileHandler("auditLog.txt");
        
        String appointmentLocation = tfAppointmentLocation.getText();
        String customerFeedback = taCustomerFeedback.getText();
        
        Date selectedDate = jdAppointmentDate.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String appointmentDate = sdf.format(selectedDate);
        
        String selectedTime = cbAppointmentStartTime.getSelectedItem().toString();
        LocalTime appointmentStartTime = LocalTime.parse(selectedTime);
        LocalDateTime now = LocalDateTime.now();
        
        LocalDate selectedDateCheck = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDateTime selectedDateTime = LocalDateTime.of(selectedDateCheck, appointmentStartTime);
        
        
        
        if(appointmentLocation.isBlank()) {
            JOptionPane.showMessageDialog(null, "Appointment Location is Empty!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (selectedDate == null) {
            JOptionPane.showMessageDialog(null, "Appointment Date not Selected!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (customerFeedback.isBlank()) {
            JOptionPane.showMessageDialog(null, "Customer Comment not Provided!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else if(selectedDateTime.isBefore(now)) {
            JOptionPane.showMessageDialog(null, "Selected Time has Passed!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String appointmentID = fh.generateNextID("AP");
            String feedbackID = fh2.generateNextID("FB");
            String appointmentStatus = "REQUESTED";
            String appointmentPaymentStatus = "UNPAID";
            
            Customer customer = (Customer) loadCurrentUser();
            
            Appointment appointment = new Appointment(
                    appointmentID,
                    appointmentLocation,
                    "null",
                    appointmentDate,
                    appointmentStartTime,
                    (LocalTime) null,
                    appointmentStatus,
                    appointmentPaymentStatus,
                    (Technician) null,
                    customer,
                    (CounterStaff) null
                );
            
            Feedback feedback = new Feedback(
                    feedbackID,
                    customerFeedback,
                    "null",
                    appointment,
                    customer,
                    (Technician) null
                );
            
            fh.writeRecord(appointment);
            fh2.writeRecord(feedback);
            
            AuditLog.log(fh3, fh3.generateNextID("AD"), customer.getUserID(), "REQUEST", appointmentID, "REQUEST APPOINTMENT");
            AuditLog.log(fh3, fh3.generateNextID("AD"), customer.getUserID(), "CREATE", appointmentID, "CREATE CUSTOMER FEEDBACK");
            
            dh.loadUsers();
            dh.loadAppointments();
            dh.loadFeedback();
            loadAppointmentTable();
            
            tfAppointmentLocation.setText("");
            taCustomerFeedback.setText("");
            jdAppointmentDate.setDate(null);
            
            JOptionPane.showMessageDialog(null, "Successfully Requested Appointment!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ex) {
            System.getLogger(CustomerScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_bRequestAppointmentActionPerformed

    private void bPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPayActionPerformed

        FileHandler fh = new FileHandler("payment.txt");
        FileHandler fh2 = new FileHandler("appointment.txt");
        FileHandler fh3 = new FileHandler("auditLog.txt");
        
        Double price = Double.parseDouble(tfPayAppointmentPrice.getText());
        String paymentDate = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        String appointmentID = tfPayAppointmentID.getText();
        
       if(appointmentID.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Please select an appointment!", "ERROR", JOptionPane.ERROR_MESSAGE);
           return;
       }
        
        try {
            String paymentID = fh.generateNextID("PY");
            Customer customer = (Customer) loadCurrentUser();
            Appointment appointment = dh.getAppointmentByID(appointmentID);
    
            Payment payment = new Payment(
                    paymentID,
                    price,
                    paymentDate,
                    "SUBMITTED",
                    appointment,
                    customer,
                    (CounterStaff) null
                    );
            
            appointment.setAppointmentPaymentStatus("PENDING");
            
            fh.writeRecord(payment);
            fh2.updateRecord(tfPayAppointmentID.getText(), appointment.toString());
            
            AuditLog.log(fh3, fh3.generateNextID("AD"), customer.getUserID(), "SUBMIT", paymentID, "SUBMIT PAYMENT");
            
            dh.loadAppointments();
            dh.loadPayments();
            loadPaymentTable();
            
            tfPayAppointmentID.setText("");
            tfPayAppointmentStartTime.setText("");
            tfPayAppointmentEndTime.setText("");
            tfPayAppointmentPrice.setText("");
            
            JOptionPane.showMessageDialog(null, "Payment Submitted!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ex) {
            System.getLogger(CustomerScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
    }//GEN-LAST:event_bPayActionPerformed
    
    private User loadCurrentUser() throws FileNotFoundException, IOException {
        String currentUserID = null;
        
        try(BufferedReader br = new BufferedReader(new FileReader("login.txt"))){
            String line = br.readLine();
            
            if(line != null) {
                String [] records = line.split("\\|");
                currentUserID = records [0].trim();      
            }
            
            return dh.getUserByID(currentUserID);
        }
    }
    
    private void loadAppointmentTable() throws IOException {
        Appointment [] appointments = dh.getAppointmentByStatus("REQUESTED");
        
        DefaultTableModel model = (DefaultTableModel) tAppointments.getModel();
        model.setRowCount(0);
        
        String customerID = loadCurrentUser().getUserID();
        
        for (Appointment a : appointments) {
            
            if (a == null) continue;
            
            if (a.getCustomer() == null) continue;

            if (!a.getCustomer().getUserID().equalsIgnoreCase(customerID)) continue;
            
            model.addRow(new Object[] {
                a.getAppointmentID(),
                a.getAppointmentLocation(),
                a.getAppointmentDate(),
                a.getAppointmentStartTime(),
                "Delete"
            });
        }
    }
    
    private void loadPaymentTable() throws IOException {
        Appointment [] appointments = dh.getAppointmentByPaymentStatus("UNPAID");
        
        DefaultTableModel model = (DefaultTableModel) tPayments.getModel();
        model.setRowCount(0);
        
        String customerID = loadCurrentUser().getUserID();
        
        for (Appointment a : appointments) {
            
            if (a == null) continue;
            
            if (a.getCustomer() == null) continue;

            if (!a.getCustomer().getUserID().equalsIgnoreCase(customerID)) continue;
            
            if (!"CLOSED".equalsIgnoreCase(a.getAppointmentStatus())) continue;
            
            model.addRow(new Object[] {
                a.getAppointmentID(),
                a.getAppointmentDate(),
                a.getAppointmentType(),
                a.getAppointmentLocation(),
                "Select"
            });
        }
    }
    
     private void onStart() throws FileNotFoundException, IOException{
        
        dh.loadUsers();
        dh.loadAppointments();
        dh.loadFeedback();
        dh.loadPayments();
        User user = loadCurrentUser();
         
        String username = user.getUsername();
        String password = user.getPassword();
        String role = user.getUserRole();
        String id = user.getUserID();
        
        lUser.setText(username);
        tfCurrentID.setText(id);
        tfCurrentRole.setText(role);
        tfUsername.setText(username);
        tfPassword.setText(password);
        
        loadAppointmentTable();
        loadPaymentTable();
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CustomerScreen().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(CustomerScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }
    
    class ButtonRenderer extends JButton implements TableCellRenderer {
        

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "" : value.toString());
            return this;
        }
        
    }
    
    class AppointmentDeleteButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("appointment.txt");
        private FileHandler fh2 = new FileHandler("feedback.txt");
        private FileHandler fh3 = new FileHandler("auditLog.txt");
        
        public AppointmentDeleteButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Delete");
            
            button.addActionListener(e -> {
                
                int confirm = JOptionPane.showConfirmDialog(null, "Delete this appointment?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                fireEditingStopped();
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String appointmentID = table.getValueAt(row, 0).toString();
                String feedbackID = dh.getFeedbackByAppointmentID(appointmentID).getFeedbackID();
                try {
                    Customer customer = (Customer) loadCurrentUser();
                    fh2.deleteRecord(feedbackID);
                    fh.deleteRecord(appointmentID);
                    ((DefaultTableModel) table.getModel()).removeRow(row);
                    
                    AuditLog.log(fh3, fh3.generateNextID("AD"), customer.getUserID(), "DELETE", appointmentID, "DELETE APPOINTMENT");
                    
                    JOptionPane.showMessageDialog(null, "Appointment successfully deleted", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                  
                    //load Feedback Table 
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            });
            
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Delete";
        }
    }
    
    class PayAppointmentSelectButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private Appointment appointment;
        private LocalTime time;
        
        public PayAppointmentSelectButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Select");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String appointmentID = table.getValueAt(row, 0).toString(); 
                
                appointment = dh.getAppointmentByID(appointmentID);
                
                try {
                    tfPayAppointmentID.setText(appointmentID);  
                    tfPayAppointmentStartTime.setText(appointment.getAppointmentStartTime().format(DateTimeFormatter.ofPattern("HH:mm")));
                    tfPayAppointmentEndTime.setText(appointment.getAppointmentEndTime().format(DateTimeFormatter.ofPattern("HH:mm")));
                    tfPayAppointmentPrice.setText(dh.ObtainPrice(appointment.getAppointmentType()));
                    
                } catch (IOException ex) {
                    System.getLogger(CustomerScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                
                
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Select";
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bPay;
    private javax.swing.JButton bRequestAppointment;
    private javax.swing.JButton bUpdateData;
    private javax.swing.JComboBox<String> cbAppointmentStartTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdAppointmentDate;
    private javax.swing.JLabel lAppointmentDate;
    private javax.swing.JLabel lAppointmentLocation;
    private javax.swing.JLabel lAppointmentStartTime;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lComments;
    private javax.swing.JLabel lCurrentPassword;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lPayAppointmentEndTime;
    private javax.swing.JLabel lPayAppointmentID;
    private javax.swing.JLabel lPayAppointmentPrice;
    private javax.swing.JLabel lPayAppointmentStartTime;
    private javax.swing.JLabel lRole;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel pHistory;
    private javax.swing.JPanel pMakeAppointment;
    private javax.swing.JPanel pMakePayment;
    private javax.swing.JPanel pProfile;
    private javax.swing.JPanel pViewFeedback;
    private javax.swing.JTable tAppointments;
    private javax.swing.JTable tPayments;
    private javax.swing.JTextArea taCustomerFeedback;
    private javax.swing.JTextField tfAppointmentLocation;
    private javax.swing.JTextField tfCurrentID;
    private javax.swing.JPasswordField tfCurrentPassword;
    private javax.swing.JTextField tfCurrentRole;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfPayAppointmentEndTime;
    private javax.swing.JTextField tfPayAppointmentID;
    private javax.swing.JTextField tfPayAppointmentPrice;
    private javax.swing.JTextField tfPayAppointmentStartTime;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTabbedPane tpTabs;
    // End of variables declaration//GEN-END:variables
}
