
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class LoginScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginScreen.class.getName());

    /**
     * Creates new form LoginScreen1
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        tfID = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        bToRegister = new javax.swing.JButton();
        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lID = new javax.swing.JLabel();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1014, 520));
        setPreferredSize(new java.awt.Dimension(1014, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(1014, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfUsername.setToolTipText("");
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 330, 30));

        tfID.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfID.setToolTipText("");
        getContentPane().add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 330, 30));
        getContentPane().add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 330, 30));

        bLogin.setText("Login");
        bLogin.setBorder(null);
        bLogin.setBorderPainted(false);
        bLogin.addActionListener(this::bLoginActionPerformed);
        getContentPane().add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 100, 40));

        bToRegister.setText("To Register");
        bToRegister.setBorder(null);
        bToRegister.setBorderPainted(false);
        bToRegister.setFocusPainted(false);
        bToRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bToRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(bToRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 100, 40));

        lUsername.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lUsername.setText("USERNAME:");
        getContentPane().add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        lPassword.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lPassword.setText("PASSWORD:");
        getContentPane().add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));
        lPassword.getAccessibleContext().setAccessibleName("USERNAME:");

        lID.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lID.setText("ID:");
        getContentPane().add(lID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Login.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bToRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bToRegisterMouseClicked
        RegisterScreen rs = new RegisterScreen();
        rs.show();
        dispose();
    }//GEN-LAST:event_bToRegisterMouseClicked

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        String loginID = tfID.getText().trim();
        String loginUsername = tfUsername.getText().trim();
        String loginPassword = tfPassword.getText().trim();
        
        boolean valid = true;
        
        if(loginID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID field is empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if(loginUsername.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username field is empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (loginPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password field is empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (loginID.isEmpty() && loginUsername.isEmpty() && loginPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Login fields are empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (loginID.length() != 8) {
            JOptionPane.showMessageDialog(null, "Invalid ID", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        
        if(!valid) return;
        
        DataHandler dh = new DataHandler();
        
        try {
            User user = dh.Login(loginID, loginUsername, loginPassword);
            
            if(user != null) {
                JOptionPane.showMessageDialog(null, "Login Successful", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                String role = user.getUserRole();
                
                switch(role) {
                    case "CUSTOMER":
                        //to customer screen
                        break;
                    case "TECHNICIAN":
                        //to technician screen
                        break;
                    case "COUNTERSTAFF":
                        //to counter staff screen
                        break;
                    case "MANAGER":
                        //to manager screen
                        break;
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Login Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (IOException ex) {
            System.getLogger(LoginScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bToRegister;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JTextField tfID;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
