
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class ManagerScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerScreen.class.getName());
    private DataHandler dh = new DataHandler();
    private ExportHandler eh = new ExportHandler();

    /**
     * Creates new form ManagerScreen
     */
    public ManagerScreen() throws IOException {
        initComponents();
        
        tUsers.getColumnModel().getColumn(4)
            .setCellRenderer(new ButtonRenderer());
        tUsers.getColumnModel().getColumn(4)
            .setCellEditor(new UserUpdateButtonEditor(new JCheckBox(), tUsers));
        
        tUsers.getColumnModel().getColumn(5)
            .setCellRenderer(new ButtonRenderer());
        tUsers.getColumnModel().getColumn(5)
            .setCellEditor(new UserDeleteButtonEditor(new JCheckBox(), tUsers));
        
        onStart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bExit = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();
        tpTabs = new javax.swing.JTabbedPane();
        pManageUsers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tUsers = new javax.swing.JTable();
        tfNewUserUsername = new javax.swing.JTextField();
        tfNewUserPassword = new javax.swing.JPasswordField();
        tfNewUserID = new javax.swing.JTextField();
        cbNewUserRole = new javax.swing.JComboBox<>();
        cbFilterTable = new javax.swing.JComboBox<>();
        lNewUserUsername = new javax.swing.JLabel();
        lNewUserPassword = new javax.swing.JLabel();
        lNewUserID = new javax.swing.JLabel();
        lNewUserRole = new javax.swing.JLabel();
        bCreateUser = new javax.swing.JButton();
        bFilter = new javax.swing.JButton();
        pSetServicePrice = new javax.swing.JPanel();
        pViewFeedbacksAndComments = new javax.swing.JPanel();
        pViewReport = new javax.swing.JPanel();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bExit.setBackground(new java.awt.Color(255, 51, 51));
        bExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(this::bExitActionPerformed);
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 50));

        lUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        pManageUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Password", "Role", "Action", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tUsers);
        if (tUsers.getColumnModel().getColumnCount() > 0) {
            tUsers.getColumnModel().getColumn(0).setResizable(false);
            tUsers.getColumnModel().getColumn(1).setResizable(false);
            tUsers.getColumnModel().getColumn(2).setResizable(false);
            tUsers.getColumnModel().getColumn(3).setResizable(false);
            tUsers.getColumnModel().getColumn(4).setResizable(false);
            tUsers.getColumnModel().getColumn(5).setResizable(false);
        }

        pManageUsers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 650, 270));
        pManageUsers.add(tfNewUserUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 40));
        pManageUsers.add(tfNewUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 170, 40));
        pManageUsers.add(tfNewUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        cbNewUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MANAGER", "COUNTER STAFF", "TECHNICIAN" }));
        pManageUsers.add(cbNewUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, 40));

        cbFilterTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "MANAGER", "COUNTER STAFF", "TECHNICIAN" }));
        pManageUsers.add(cbFilterTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 130, 30));

        lNewUserUsername.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserUsername.setText("USERNAME");
        pManageUsers.add(lNewUserUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 20));

        lNewUserPassword.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserPassword.setText("PASSWORD");
        pManageUsers.add(lNewUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, -1));

        lNewUserID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserID.setText("USER ID");
        pManageUsers.add(lNewUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 20));

        lNewUserRole.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserRole.setText("ROLE");
        pManageUsers.add(lNewUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        bCreateUser.setBackground(new java.awt.Color(255, 204, 255));
        bCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCreateUser.setText("CREATE USER");
        bCreateUser.addActionListener(this::bCreateUserActionPerformed);
        pManageUsers.add(bCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 150, 50));

        bFilter.setBackground(new java.awt.Color(255, 204, 255));
        bFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bFilter.setText("FILTER");
        bFilter.addActionListener(this::bFilterActionPerformed);
        pManageUsers.add(bFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, 30));

        tpTabs.addTab("Manage Users", pManageUsers);

        javax.swing.GroupLayout pSetServicePriceLayout = new javax.swing.GroupLayout(pSetServicePrice);
        pSetServicePrice.setLayout(pSetServicePriceLayout);
        pSetServicePriceLayout.setHorizontalGroup(
            pSetServicePriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pSetServicePriceLayout.setVerticalGroup(
            pSetServicePriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tpTabs.addTab("Set Service Price", pSetServicePrice);

        javax.swing.GroupLayout pViewFeedbacksAndCommentsLayout = new javax.swing.GroupLayout(pViewFeedbacksAndComments);
        pViewFeedbacksAndComments.setLayout(pViewFeedbacksAndCommentsLayout);
        pViewFeedbacksAndCommentsLayout.setHorizontalGroup(
            pViewFeedbacksAndCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pViewFeedbacksAndCommentsLayout.setVerticalGroup(
            pViewFeedbacksAndCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tpTabs.addTab("View Feedbacks & Comments", pViewFeedbacksAndComments);

        javax.swing.GroupLayout pViewReportLayout = new javax.swing.GroupLayout(pViewReport);
        pViewReport.setLayout(pViewReportLayout);
        pViewReportLayout.setHorizontalGroup(
            pViewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pViewReportLayout.setVerticalGroup(
            pViewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tpTabs.addTab("View Report", pViewReport);

        getContentPane().add(tpTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 740, 500));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Manager Screen.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.show();
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFilterActionPerformed
        
        String filter = cbFilterTable.getSelectedItem().toString().trim().replace(" ", "");
        
        if(filter.equals("ALL")) {
            loadUserTable("MANAGER", "COUNTERSTAFF", "TECHNICIAN");
        } else {
            loadUserTable(filter);
        }
        
    }//GEN-LAST:event_bFilterActionPerformed

    private void bCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateUserActionPerformed
        String newID = tfNewUserID.getText();
        String newUsername = tfNewUserUsername.getText();
        String newPassword = tfNewUserPassword.getText();
        String newRole = cbNewUserRole.getSelectedItem().toString().trim().replace(" ", "");
        
        FileHandler fh = new FileHandler("user.txt");
        
        User u;
        
        try {
            u = dh.RegisterUser(newID, newUsername, newPassword, newRole);
            if(!fh.doesRecordExists(u)) {
                fh.writeRecord(u);
                dh.loadUsers();
                JOptionPane.showMessageDialog(null, "User successfully created", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                loadUserTable(newRole);   
            } else {
                JOptionPane.showMessageDialog(null, "User already exists!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        tfNewUserPassword.setText("");
        tfNewUserUsername.setText("");
        tfNewUserID.setText("");
        
    }//GEN-LAST:event_bCreateUserActionPerformed
    
    private User loadCurrentUser() throws FileNotFoundException, IOException {
        String currentUserID = null;
        
        try(BufferedReader br = new BufferedReader(new FileReader("login.txt"))){
            String line = br.readLine();
            
            if(line != null) {
                String [] records = line.split("\\|");
                currentUserID = records [0].trim();      
            }
            
            return dh.getUserByID(currentUserID);
        }
    }
    
    private void loadUserTable(String... filter) {
        
        User [] users = dh.getUserByRoles(filter);
        
        DefaultTableModel model = (DefaultTableModel) tUsers.getModel();
        model.setRowCount(0);
        
        for (User u : users) {
            model.addRow(new Object[]{
                u.getUserID(),
                u.getUsername(),
                u.getPassword(),
                u.getUserRole(),
                "Update",
                "Delete"
            });
        }
    }
    
    private void onStart() throws FileNotFoundException, IOException{
        
        dh.loadUsers();
        dh.loadAppointments();
        dh.loadFeedback();
        dh.loadPayments();
        User user = loadCurrentUser();
         
        String username = user.getUsername();
        
        lUser.setText(username);
        loadUserTable("MANAGER", "COUNTERSTAFF", "TECHNICIAN");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ManagerScreen().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(ManagerScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }
    
    class ButtonRenderer extends JButton implements TableCellRenderer {
        

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "" : value.toString());
            return this;
        }
        
    }
    
    class UserUpdateButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");
        
        public UserUpdateButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Update");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                int confirm = JOptionPane.showConfirmDialog(null, "Update this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                String username = table.getValueAt(row, 1).toString();
                String password = table.getValueAt(row, 2).toString();
                String role = table.getValueAt(row, 3).toString();
                
                User user = dh.getUserByID(userID);
                
                user.setUsername(username);
                user.setPassword(password);
                
                String newRecord = user.toString();
                
                try {
                    fh.updateRecord(userID, newRecord);
                    JOptionPane.showMessageDialog(null, "User successfully updated", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                    dh.loadUsers();
                    dh.loadFeedback();
                    loadUserTable(role);
                    //loadFeedbackTable();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
  
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Update";
        }
    }
    
    class UserDeleteButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");

        public UserDeleteButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Delete");
            
            button.addActionListener(e -> {
                
                int confirm = JOptionPane.showConfirmDialog(null, "Delete this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                fireEditingStopped();
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                
                try {
                    Appointment [] appointments = dh.getAppointmentByTechnicianID(userID);
                    
                    if(dh.hasAssignedAppointment(appointments)) {
                        JOptionPane.showMessageDialog(null, "Cannot delete Technician. Technician has assigned appointments!", "ERROR", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    fh.deleteRecord(userID);
                    ((DefaultTableModel) table.getModel()).removeRow(row);
                    JOptionPane.showMessageDialog(null, "User successfully deleted", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                  
                    dh.loadUsers();
                    
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            });
            
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Delete";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreateUser;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bFilter;
    private javax.swing.JComboBox<String> cbFilterTable;
    private javax.swing.JComboBox<String> cbNewUserRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lNewUserID;
    private javax.swing.JLabel lNewUserPassword;
    private javax.swing.JLabel lNewUserRole;
    private javax.swing.JLabel lNewUserUsername;
    private javax.swing.JLabel lUser;
    private javax.swing.JPanel pManageUsers;
    private javax.swing.JPanel pSetServicePrice;
    private javax.swing.JPanel pViewFeedbacksAndComments;
    private javax.swing.JPanel pViewReport;
    private javax.swing.JTable tUsers;
    private javax.swing.JTextField tfNewUserID;
    private javax.swing.JPasswordField tfNewUserPassword;
    private javax.swing.JTextField tfNewUserUsername;
    private javax.swing.JTabbedPane tpTabs;
    // End of variables declaration//GEN-END:variables
}
