
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class ManagerScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerScreen.class.getName());
    private DataHandler dh = new DataHandler();
    private ExportHandler eh = new ExportHandler();

    /**
     * Creates new form ManagerScreen
     */
    public ManagerScreen() throws IOException {
        initComponents();
        pViewReport.setLayout(new BoxLayout(pViewReport, BoxLayout.Y_AXIS));
        
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(sNormalServicePrice, "0.00");
        JSpinner.NumberEditor editor2 = new JSpinner.NumberEditor(sMajorServicePrice, "0.00");
        sNormalServicePrice.setEditor(editor);
        sMajorServicePrice.setEditor(editor2);
        
        tUsers.getColumnModel().getColumn(4)
            .setCellRenderer(new ButtonRenderer());
        tUsers.getColumnModel().getColumn(4)
            .setCellEditor(new UserUpdateButtonEditor(new JCheckBox(), tUsers));
        
        tUsers.getColumnModel().getColumn(5)
            .setCellRenderer(new ButtonRenderer());
        tUsers.getColumnModel().getColumn(5)
            .setCellEditor(new UserDeleteButtonEditor(new JCheckBox(), tUsers));
        
        tFeedbacks.getColumnModel().getColumn(4)
            .setCellRenderer(new ButtonRenderer());
        tFeedbacks.getColumnModel().getColumn(4)
            .setCellEditor(new FeedbackSelectButtonEditor(new JCheckBox(), tFeedbacks));
        
        onStart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bExit = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();
        tpTabs = new javax.swing.JTabbedPane();
        pManageUsers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tUsers = new javax.swing.JTable();
        tfNewUserUsername = new javax.swing.JTextField();
        tfNewUserPassword = new javax.swing.JPasswordField();
        tfNewUserID = new javax.swing.JTextField();
        cbNewUserRole = new javax.swing.JComboBox<>();
        cbFilterTable = new javax.swing.JComboBox<>();
        lNewUserUsername = new javax.swing.JLabel();
        lNewUserPassword = new javax.swing.JLabel();
        lNewUserID = new javax.swing.JLabel();
        lNewUserRole = new javax.swing.JLabel();
        bCreateUser = new javax.swing.JButton();
        bFilter = new javax.swing.JButton();
        pSetServicePrice = new javax.swing.JPanel();
        sNormalServicePrice = new javax.swing.JSpinner();
        sMajorServicePrice = new javax.swing.JSpinner();
        lNormalServicePrice = new javax.swing.JLabel();
        lMajorServicePrice = new javax.swing.JLabel();
        bSetPrice = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tPrices = new javax.swing.JTable();
        pViewFeedbacksAndComments = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tFeedbacks = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        taCustomerFeedback = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taTechnicianFeedback = new javax.swing.JTextArea();
        lCustomerFeedback = new javax.swing.JLabel();
        lTechnicianFeedback = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        pViewReport = new javax.swing.JPanel();
        pAppointmentCountBarChart = new javax.swing.JPanel();
        pPaymentStatusPieChart = new javax.swing.JPanel();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bExit.setBackground(new java.awt.Color(255, 51, 51));
        bExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(this::bExitActionPerformed);
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 50));

        lUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        pManageUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Password", "Role", "Action", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tUsers);
        if (tUsers.getColumnModel().getColumnCount() > 0) {
            tUsers.getColumnModel().getColumn(0).setResizable(false);
            tUsers.getColumnModel().getColumn(1).setResizable(false);
            tUsers.getColumnModel().getColumn(2).setResizable(false);
            tUsers.getColumnModel().getColumn(3).setResizable(false);
            tUsers.getColumnModel().getColumn(4).setResizable(false);
            tUsers.getColumnModel().getColumn(5).setResizable(false);
        }

        pManageUsers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 650, 270));
        pManageUsers.add(tfNewUserUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 40));
        pManageUsers.add(tfNewUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 170, 40));
        pManageUsers.add(tfNewUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        cbNewUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MANAGER", "COUNTER STAFF", "TECHNICIAN" }));
        pManageUsers.add(cbNewUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, 40));

        cbFilterTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "MANAGER", "COUNTER STAFF", "TECHNICIAN" }));
        pManageUsers.add(cbFilterTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 130, 30));

        lNewUserUsername.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserUsername.setText("USERNAME");
        pManageUsers.add(lNewUserUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 20));

        lNewUserPassword.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserPassword.setText("PASSWORD");
        pManageUsers.add(lNewUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, -1));

        lNewUserID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserID.setText("USER ID");
        pManageUsers.add(lNewUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 20));

        lNewUserRole.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNewUserRole.setText("ROLE");
        pManageUsers.add(lNewUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        bCreateUser.setBackground(new java.awt.Color(255, 204, 255));
        bCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCreateUser.setText("CREATE USER");
        bCreateUser.addActionListener(this::bCreateUserActionPerformed);
        pManageUsers.add(bCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 150, 50));

        bFilter.setBackground(new java.awt.Color(255, 204, 255));
        bFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bFilter.setText("FILTER");
        bFilter.addActionListener(this::bFilterActionPerformed);
        pManageUsers.add(bFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, 30));

        tpTabs.addTab("Manage Users", pManageUsers);

        pSetServicePrice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sNormalServicePrice.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10000.0d, 0.5d));
        sNormalServicePrice.setDoubleBuffered(true);
        pSetServicePrice.add(sNormalServicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 190, 50));

        sMajorServicePrice.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10000.0d, 0.5d));
        pSetServicePrice.add(sMajorServicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 190, 50));

        lNormalServicePrice.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lNormalServicePrice.setText("NORMAL SERVICE PRICE");
        pSetServicePrice.add(lNormalServicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, 30));

        lMajorServicePrice.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lMajorServicePrice.setText("MAJOR SERVICE PRICE");
        pSetServicePrice.add(lMajorServicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, 30));

        bSetPrice.setBackground(new java.awt.Color(255, 204, 255));
        bSetPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSetPrice.setText("SET PRICE");
        bSetPrice.addActionListener(this::bSetPriceActionPerformed);
        pSetServicePrice.add(bSetPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 150, 50));

        tPrices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Normal Service Price", "Major Service Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tPrices);
        if (tPrices.getColumnModel().getColumnCount() > 0) {
            tPrices.getColumnModel().getColumn(0).setResizable(false);
            tPrices.getColumnModel().getColumn(1).setResizable(false);
        }

        pSetServicePrice.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 580, 50));

        tpTabs.addTab("Set Service Price", pSetServicePrice);

        pViewFeedbacksAndComments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tFeedbacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Feedback ID", "Appointment ID", "Customer Name", "Technician Name", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tFeedbacks);
        if (tFeedbacks.getColumnModel().getColumnCount() > 0) {
            tFeedbacks.getColumnModel().getColumn(0).setResizable(false);
            tFeedbacks.getColumnModel().getColumn(1).setResizable(false);
            tFeedbacks.getColumnModel().getColumn(2).setResizable(false);
            tFeedbacks.getColumnModel().getColumn(3).setResizable(false);
            tFeedbacks.getColumnModel().getColumn(4).setResizable(false);
        }

        pViewFeedbacksAndComments.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 610, 220));

        taCustomerFeedback.setEditable(false);
        taCustomerFeedback.setColumns(20);
        taCustomerFeedback.setRows(5);
        taCustomerFeedback.setAutoscrolls(false);
        taCustomerFeedback.setEnabled(false);
        taCustomerFeedback.setFocusable(false);
        taCustomerFeedback.setRequestFocusEnabled(false);
        taCustomerFeedback.setVerifyInputWhenFocusTarget(false);
        jScrollPane3.setViewportView(taCustomerFeedback);

        pViewFeedbacksAndComments.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        taTechnicianFeedback.setEditable(false);
        taTechnicianFeedback.setColumns(20);
        taTechnicianFeedback.setRows(5);
        taTechnicianFeedback.setEnabled(false);
        taTechnicianFeedback.setFocusable(false);
        taTechnicianFeedback.setOpaque(false);
        taTechnicianFeedback.setRequestFocusEnabled(false);
        taTechnicianFeedback.setVerifyInputWhenFocusTarget(false);
        jScrollPane4.setViewportView(taTechnicianFeedback);

        pViewFeedbacksAndComments.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        lCustomerFeedback.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lCustomerFeedback.setText("CUSTOMER COMMENT");
        pViewFeedbacksAndComments.add(lCustomerFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 150, 30));

        lTechnicianFeedback.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lTechnicianFeedback.setText("TECHNICIAN FEEDBACK");
        pViewFeedbacksAndComments.add(lTechnicianFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 180, 30));

        tpTabs.addTab("View Feedbacks & Comments", pViewFeedbacksAndComments);

        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pViewReport.setLayout(new javax.swing.BoxLayout(pViewReport, javax.swing.BoxLayout.LINE_AXIS));

        pAppointmentCountBarChart.setMaximumSize(new java.awt.Dimension(500, 400));
        pAppointmentCountBarChart.setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout pAppointmentCountBarChartLayout = new javax.swing.GroupLayout(pAppointmentCountBarChart);
        pAppointmentCountBarChart.setLayout(pAppointmentCountBarChartLayout);
        pAppointmentCountBarChartLayout.setHorizontalGroup(
            pAppointmentCountBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        pAppointmentCountBarChartLayout.setVerticalGroup(
            pAppointmentCountBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        pViewReport.add(pAppointmentCountBarChart);

        pPaymentStatusPieChart.setMaximumSize(new java.awt.Dimension(500, 400));
        pPaymentStatusPieChart.setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout pPaymentStatusPieChartLayout = new javax.swing.GroupLayout(pPaymentStatusPieChart);
        pPaymentStatusPieChart.setLayout(pPaymentStatusPieChartLayout);
        pPaymentStatusPieChartLayout.setHorizontalGroup(
            pPaymentStatusPieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        pPaymentStatusPieChartLayout.setVerticalGroup(
            pPaymentStatusPieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        pViewReport.add(pPaymentStatusPieChart);

        jScrollPane6.setViewportView(pViewReport);

        tpTabs.addTab("View Report", jScrollPane6);

        getContentPane().add(tpTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 740, 500));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Manager Screen.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.show();
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFilterActionPerformed
        
        String filter = cbFilterTable.getSelectedItem().toString().trim().replace(" ", "");
        
        if(filter.equals("ALL")) {
            loadUserTable("MANAGER", "COUNTERSTAFF", "TECHNICIAN");
        } else {
            loadUserTable(filter);
        }
        
    }//GEN-LAST:event_bFilterActionPerformed

    private void bCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateUserActionPerformed
        String newID = tfNewUserID.getText();
        String newUsername = tfNewUserUsername.getText();
        String newPassword = tfNewUserPassword.getText();
        String newRole = cbNewUserRole.getSelectedItem().toString().trim().replace(" ", "");
        
        FileHandler fh = new FileHandler("user.txt");
        
        User u;
        
        try {
            u = dh.RegisterUser(newID, newUsername, newPassword, newRole);
            if(!fh.doesRecordExists(u)) {
                fh.writeRecord(u);
                dh.loadUsers();
                JOptionPane.showMessageDialog(null, "User successfully created", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                loadUserTable(newRole);   
            } else {
                JOptionPane.showMessageDialog(null, "User already exists!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        tfNewUserPassword.setText("");
        tfNewUserUsername.setText("");
        tfNewUserID.setText("");
        
    }//GEN-LAST:event_bCreateUserActionPerformed

    private void bSetPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetPriceActionPerformed
        double normalServicePrice = (double) sNormalServicePrice.getValue();
        double majorServicePrice = (double) sMajorServicePrice.getValue();
        
        String normalServicePriceString = String.format("%.2f", normalServicePrice);
        String majorServicePriceString = String.format("%.2f", majorServicePrice);

        String priceRecord = normalServicePriceString + "|" + majorServicePriceString;
        
        FileHandler fh = new FileHandler("servicePrice.txt");
        
        try {
            fh.writePriceRecord(priceRecord);
            loadPriceTable();
            JOptionPane.showMessageDialog(null, "Price Successfully Set!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.getLogger(ManagerScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_bSetPriceActionPerformed
    
    private User loadCurrentUser() throws FileNotFoundException, IOException {
        String currentUserID = null;
        
        try(BufferedReader br = new BufferedReader(new FileReader("login.txt"))){
            String line = br.readLine();
            
            if(line != null) {
                String [] records = line.split("\\|");
                currentUserID = records [0].trim();      
            }
            
            return dh.getUserByID(currentUserID);
        }
    }
    
    private void loadUserTable(String... filter) {
        
        User [] users = dh.getUserByRoles(filter);
        
        DefaultTableModel model = (DefaultTableModel) tUsers.getModel();
        model.setRowCount(0);
        
        for (User u : users) {
            model.addRow(new Object[]{
                u.getUserID(),
                u.getUsername(),
                u.getPassword(),
                u.getUserRole(),
                "Update",
                "Delete"
            });
        }
    }
    
    private void loadFeedbackTable() {
        
        Appointment [] appointments = dh.getAppointmentByStatus("CLOSED");
        
        String[] ids = new String[appointments.length];
        int count = 0;

        for (Appointment a : appointments) {
            if (a != null) {
                ids[count++] = a.getAppointmentID();
            }
        }

        ids = java.util.Arrays.copyOf(ids, count);
        
        Feedback [] feedbacks = dh.getFeedbacksByAppointmentID(ids);
        
        DefaultTableModel model = (DefaultTableModel) tFeedbacks.getModel();
        model.setRowCount(0);
        
        for (Feedback f : feedbacks) {
            model.addRow(new Object[]{
                f.getFeedbackID(),
                f.getAppointment().getAppointmentID(),
                (f.getCustomer() == null) ? "DELETED USER" : f.getCustomer().getUsername(),
                (f.getTechnician() ==  null) ? "DELETED TECHNICIAN" : f.getTechnician().getUsername(),
                "Select"
            });
        }
    }
    
    private void loadPriceTable() throws FileNotFoundException, IOException {
        
        DefaultTableModel model = (DefaultTableModel) tPrices.getModel();
        model.setRowCount(0);
        
        try(BufferedReader br = new BufferedReader(new FileReader("servicePrice.txt"))) {
            
            String line;
            
            while((line = br.readLine()) != null) {
                String [] records = line.split("\\|");
                
                model.addRow(new Object[]{records[0], records[1]});
            }
        }
    }
    
    private void loadAppointmentChart() {
        try {
            DefaultCategoryDataset dataset = dh.createMonthlyDataset();

            JFreeChart chart = ChartFactory.createBarChart(
                "Appointments per Month",
                "Month",
                "Number of Appointments",
                dataset
            );

            ChartPanel chartPanel = new ChartPanel(chart);

            pAppointmentCountBarChart.removeAll();
            pAppointmentCountBarChart.setLayout(new BorderLayout());
            pAppointmentCountBarChart.add(chartPanel, BorderLayout.CENTER);
            pAppointmentCountBarChart.revalidate();
            pAppointmentCountBarChart.repaint();
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void loadPieChart() {
        try {
            DefaultPieDataset dataset = dh.createPaymentDataset();

            JFreeChart chart = ChartFactory.createPieChart(
                "Payment Status Distribution",
                dataset,
                true,
                true,
                false
            );

            ChartPanel chartPanel = new ChartPanel(chart);

            pPaymentStatusPieChart.removeAll();
            pPaymentStatusPieChart.setLayout(new BorderLayout());
            pPaymentStatusPieChart.add(chartPanel, BorderLayout.CENTER);
            pPaymentStatusPieChart.revalidate();
            pPaymentStatusPieChart.repaint();
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void onStart() throws FileNotFoundException, IOException{
        
        dh.loadUsers();
        dh.loadAppointments();
        dh.loadFeedback();
        dh.loadPayments();
        User user = loadCurrentUser();
         
        String username = user.getUsername();
        
        lUser.setText(username);
        loadUserTable("MANAGER", "COUNTERSTAFF", "TECHNICIAN");
        loadFeedbackTable();
        loadPriceTable();
        loadAppointmentChart();
        loadPieChart();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ManagerScreen().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(ManagerScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }
    
    class ButtonRenderer extends JButton implements TableCellRenderer {
        

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "" : value.toString());
            return this;
        }
        
    }
    
    class UserUpdateButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");
        
        public UserUpdateButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Update");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                int confirm = JOptionPane.showConfirmDialog(null, "Update this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                String username = table.getValueAt(row, 1).toString();
                String password = table.getValueAt(row, 2).toString();
                String role = table.getValueAt(row, 3).toString();
                
                User user = dh.getUserByID(userID);
                
                user.setUsername(username);
                user.setPassword(password);
                
                String newRecord = user.toString();
                
                try {
                    fh.updateRecord(userID, newRecord);
                    JOptionPane.showMessageDialog(null, "User successfully updated", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                    dh.loadUsers();
                    dh.loadAppointments();
                    dh.loadFeedback();
                    loadUserTable(role);
                    loadFeedbackTable();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
  
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Update";
        }
    }
    
    class UserDeleteButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private FileHandler fh = new FileHandler("user.txt");

        public UserDeleteButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Delete");
            
            button.addActionListener(e -> {
                
                int confirm = JOptionPane.showConfirmDialog(null, "Delete this user?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm != JOptionPane.YES_OPTION) return;
                
                fireEditingStopped();
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String userID = table.getValueAt(row, 0).toString();
                
                try {
                    Appointment [] appointments = dh.getAppointmentByTechnicianID(userID);
                    
                    if(dh.hasAssignedAppointment(appointments)) {
                        JOptionPane.showMessageDialog(null, "Cannot delete Technician. Technician has assigned appointments!", "ERROR", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    fh.deleteRecord(userID);
                    ((DefaultTableModel) table.getModel()).removeRow(row);
                    JOptionPane.showMessageDialog(null, "User successfully deleted", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                  
                    dh.loadUsers();
                    dh.loadAppointments();
                    dh.loadFeedback();
                    loadFeedbackTable();
                    
                    
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            });
            
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Delete";
        }
    }
    
    class FeedbackSelectButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private Feedback feedback;
        
        public FeedbackSelectButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Select");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String feedbackID = table.getValueAt(row, 0).toString(); 
                
                feedback = dh.getFeedbackByID(feedbackID);
                
                taCustomerFeedback.setText(feedback.getCustomerFeedback());
                taTechnicianFeedback.setText(feedback.getTechnicianFeedback());
                
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Select";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreateUser;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bFilter;
    private javax.swing.JButton bSetPrice;
    private javax.swing.JComboBox<String> cbFilterTable;
    private javax.swing.JComboBox<String> cbNewUserRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lCustomerFeedback;
    private javax.swing.JLabel lMajorServicePrice;
    private javax.swing.JLabel lNewUserID;
    private javax.swing.JLabel lNewUserPassword;
    private javax.swing.JLabel lNewUserRole;
    private javax.swing.JLabel lNewUserUsername;
    private javax.swing.JLabel lNormalServicePrice;
    private javax.swing.JLabel lTechnicianFeedback;
    private javax.swing.JLabel lUser;
    private javax.swing.JPanel pAppointmentCountBarChart;
    private javax.swing.JPanel pManageUsers;
    private javax.swing.JPanel pPaymentStatusPieChart;
    private javax.swing.JPanel pSetServicePrice;
    private javax.swing.JPanel pViewFeedbacksAndComments;
    private javax.swing.JPanel pViewReport;
    private javax.swing.JSpinner sMajorServicePrice;
    private javax.swing.JSpinner sNormalServicePrice;
    private javax.swing.JTable tFeedbacks;
    private javax.swing.JTable tPrices;
    private javax.swing.JTable tUsers;
    private javax.swing.JTextArea taCustomerFeedback;
    private javax.swing.JTextArea taTechnicianFeedback;
    private javax.swing.JTextField tfNewUserID;
    private javax.swing.JPasswordField tfNewUserPassword;
    private javax.swing.JTextField tfNewUserUsername;
    private javax.swing.JTabbedPane tpTabs;
    // End of variables declaration//GEN-END:variables
}
