
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class RegisterScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginScreen.class.getName());

    /**
     * Creates new form LoginScreen1
     */
    public RegisterScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        tfID = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        bRegister = new javax.swing.JButton();
        bToLogin = new javax.swing.JButton();
        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lIDNumber = new javax.swing.JLabel();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1014, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(1014, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfUsername.setToolTipText("");
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 330, 30));

        tfID.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfID.setToolTipText("");
        getContentPane().add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 330, 30));
        getContentPane().add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 330, 30));

        bRegister.setText("Register");
        bRegister.setBorder(null);
        bRegister.setBorderPainted(false);
        bRegister.addActionListener(this::bRegisterActionPerformed);
        getContentPane().add(bRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 100, 40));

        bToLogin.setText("To Login");
        bToLogin.setBorder(null);
        bToLogin.setBorderPainted(false);
        bToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bToLoginMouseClicked(evt);
            }
        });
        getContentPane().add(bToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 100, 40));

        lUsername.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lUsername.setText("USERNAME:");
        getContentPane().add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        lPassword.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lPassword.setText("PASSWORD:");
        getContentPane().add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));
        lPassword.getAccessibleContext().setAccessibleName("USERNAME:");

        lIDNumber.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lIDNumber.setText("ID:");
        getContentPane().add(lIDNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Register.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bToLoginMouseClicked
        LoginScreen ls = new LoginScreen();
        ls.show();
        dispose();
    }//GEN-LAST:event_bToLoginMouseClicked

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        String registerID = tfID.getText().trim();
        String registerUsername = tfUsername.getText().trim();
        String registerPassword = tfPassword.getText().trim();
        String role = "CUSTOMER";
        boolean valid = true;
  
        if(registerID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID field is empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if(registerUsername.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username field is empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (registerPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password field is empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (registerID.isEmpty() && registerUsername.isEmpty() && registerPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Registration fields are empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (registerID.length() != 8) {
            JOptionPane.showMessageDialog(null, "Invalid ID", "ERROR", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        
        if(!valid) return;
        
        Customer customer = new Customer(registerID, registerUsername, registerPassword, role);
        
        FileHandler fh = new FileHandler("user.txt");
        
        try {
            if(fh.doesRecordExists(customer)) {
                JOptionPane.showMessageDialog(null, "User already exists", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if(!fh.doesRecordExists(customer)) {           
                fh.writeRecord(customer);
                JOptionPane.showMessageDialog(null, "Registration Succesful", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                //add screen transition
            } else {
                JOptionPane.showMessageDialog(null, "Registration Failed", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            System.getLogger(RegisterScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegister;
    private javax.swing.JButton bToLogin;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lIDNumber;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JTextField tfID;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
