
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ejjaz
 */
public class TechnicianScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TechnicianScreen.class.getName());
    private DataHandler dh = new DataHandler();
    private ExportHandler eh = new ExportHandler();

    /**
     * Creates new form TechnicianScreen
     */
    public TechnicianScreen() throws IOException {
        initComponents();
        
        tAppointments.getColumnModel().getColumn(3)
            .setCellRenderer(new ButtonRenderer());
        tAppointments.getColumnModel().getColumn(3)
            .setCellEditor(new AppointmentSelectButtonEditor(new JCheckBox(), tAppointments));
        
        tCompletedAppointments.getColumnModel().getColumn(3)
            .setCellRenderer(new ButtonRenderer());
        tCompletedAppointments.getColumnModel().getColumn(3)
            .setCellEditor(new CompletedAppointmentSelectButtonEditor(new JCheckBox(), tCompletedAppointments));
        
        onStart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bExit = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();
        tpTabs = new javax.swing.JTabbedPane();
        pManageAppointments = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAppointments = new javax.swing.JTable();
        tfAppointmentID = new javax.swing.JTextField();
        tfAppointmentLocation = new javax.swing.JTextField();
        tfAppointmentType = new javax.swing.JTextField();
        tfAppointmentStartTime = new javax.swing.JTextField();
        tfAppointmentEndTime = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCustomerFeedback = new javax.swing.JTextArea();
        lAppointmentID = new javax.swing.JLabel();
        lAppointmentLocation = new javax.swing.JLabel();
        lAppointmentType = new javax.swing.JLabel();
        lAppointmentStartTime = new javax.swing.JLabel();
        lAppointmentEndTime = new javax.swing.JLabel();
        lCustomerComment = new javax.swing.JLabel();
        bCompleteAppointment = new javax.swing.JButton();
        bExportSchedule = new javax.swing.JButton();
        pManageFeedback = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tCompletedAppointments = new javax.swing.JTable();
        tfCompletedAppointmentID = new javax.swing.JTextField();
        tfCompletedAppointmentLocation = new javax.swing.JTextField();
        tfCompletedAppointmentStartTime = new javax.swing.JTextField();
        tfCompletedAppointmentEndTime = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        taTechnicianFeedback = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lCompletedAppointmentLocation = new javax.swing.JLabel();
        lCompletedAppointmentStartTime = new javax.swing.JLabel();
        lCompletedAppointmentEndTime = new javax.swing.JLabel();
        lTechnicianFeedback = new javax.swing.JLabel();
        bSubmitFeedback = new javax.swing.JButton();
        pProfile = new javax.swing.JPanel();
        tfCurrentID = new javax.swing.JTextField();
        tfCurrentRole = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        tfCurrentPassword = new javax.swing.JPasswordField();
        lID = new javax.swing.JLabel();
        lRole = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lCurrentPassword = new javax.swing.JLabel();
        bUpdateData = new javax.swing.JButton();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bExit.setBackground(new java.awt.Color(255, 51, 51));
        bExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(this::bExitActionPerformed);
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 50));

        lUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        pManageAppointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Date", "Customer", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tAppointments);
        if (tAppointments.getColumnModel().getColumnCount() > 0) {
            tAppointments.getColumnModel().getColumn(0).setResizable(false);
            tAppointments.getColumnModel().getColumn(1).setResizable(false);
            tAppointments.getColumnModel().getColumn(2).setResizable(false);
            tAppointments.getColumnModel().getColumn(3).setResizable(false);
        }

        pManageAppointments.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 190));

        tfAppointmentID.setEditable(false);
        tfAppointmentID.setEnabled(false);
        tfAppointmentID.setFocusable(false);
        tfAppointmentID.setRequestFocusEnabled(false);
        tfAppointmentID.setVerifyInputWhenFocusTarget(false);
        pManageAppointments.add(tfAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 40));

        tfAppointmentLocation.setEditable(false);
        tfAppointmentLocation.setEnabled(false);
        tfAppointmentLocation.setFocusable(false);
        tfAppointmentLocation.setRequestFocusEnabled(false);
        tfAppointmentLocation.setVerifyInputWhenFocusTarget(false);
        pManageAppointments.add(tfAppointmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 40));

        tfAppointmentType.setEditable(false);
        tfAppointmentType.setEnabled(false);
        tfAppointmentType.setFocusable(false);
        tfAppointmentType.setRequestFocusEnabled(false);
        tfAppointmentType.setVerifyInputWhenFocusTarget(false);
        pManageAppointments.add(tfAppointmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 190, 40));

        tfAppointmentStartTime.setEditable(false);
        tfAppointmentStartTime.setEnabled(false);
        tfAppointmentStartTime.setFocusable(false);
        tfAppointmentStartTime.setRequestFocusEnabled(false);
        tfAppointmentStartTime.setVerifyInputWhenFocusTarget(false);
        pManageAppointments.add(tfAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 180, 40));

        tfAppointmentEndTime.setEditable(false);
        tfAppointmentEndTime.setEnabled(false);
        tfAppointmentEndTime.setFocusable(false);
        tfAppointmentEndTime.setRequestFocusEnabled(false);
        tfAppointmentEndTime.setVerifyInputWhenFocusTarget(false);
        pManageAppointments.add(tfAppointmentEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 180, 40));

        taCustomerFeedback.setEditable(false);
        taCustomerFeedback.setColumns(20);
        taCustomerFeedback.setRows(5);
        taCustomerFeedback.setEnabled(false);
        taCustomerFeedback.setFocusable(false);
        taCustomerFeedback.setRequestFocusEnabled(false);
        taCustomerFeedback.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(taCustomerFeedback);

        pManageAppointments.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 250, 110));

        lAppointmentID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentID.setText("APPOINTMENT ID");
        pManageAppointments.add(lAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 30));

        lAppointmentLocation.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentLocation.setText("APPOINTMENT LOCATION");
        pManageAppointments.add(lAppointmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 30));

        lAppointmentType.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentType.setText("APPOINTMENT TYPE");
        pManageAppointments.add(lAppointmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 160, 30));

        lAppointmentStartTime.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentStartTime.setText("APPOINTMENT START TIME");
        pManageAppointments.add(lAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 190, 30));

        lAppointmentEndTime.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lAppointmentEndTime.setText("APPOINTMENT END TIME");
        pManageAppointments.add(lAppointmentEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 180, 30));

        lCustomerComment.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lCustomerComment.setText("CUSTOMER COMMENT");
        pManageAppointments.add(lCustomerComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 150, 30));

        bCompleteAppointment.setBackground(new java.awt.Color(102, 255, 153));
        bCompleteAppointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCompleteAppointment.setText("COMPLETE APPOINTMENT");
        bCompleteAppointment.addActionListener(this::bCompleteAppointmentActionPerformed);
        pManageAppointments.add(bCompleteAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 180, 60));

        bExportSchedule.setBackground(new java.awt.Color(102, 255, 153));
        bExportSchedule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExportSchedule.setText("EXPORT SCHEDULE");
        bExportSchedule.addActionListener(this::bExportScheduleActionPerformed);
        pManageAppointments.add(bExportSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 190, 60));

        tpTabs.addTab("Manage Appointments", pManageAppointments);

        pManageFeedback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tCompletedAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Date", "Customer Name", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tCompletedAppointments);
        if (tCompletedAppointments.getColumnModel().getColumnCount() > 0) {
            tCompletedAppointments.getColumnModel().getColumn(0).setResizable(false);
            tCompletedAppointments.getColumnModel().getColumn(1).setResizable(false);
            tCompletedAppointments.getColumnModel().getColumn(3).setResizable(false);
        }

        pManageFeedback.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 630, 170));

        tfCompletedAppointmentID.setEditable(false);
        tfCompletedAppointmentID.setEnabled(false);
        tfCompletedAppointmentID.setFocusable(false);
        tfCompletedAppointmentID.setRequestFocusEnabled(false);
        pManageFeedback.add(tfCompletedAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 40));

        tfCompletedAppointmentLocation.setEditable(false);
        tfCompletedAppointmentLocation.setEnabled(false);
        tfCompletedAppointmentLocation.setFocusable(false);
        tfCompletedAppointmentLocation.setRequestFocusEnabled(false);
        tfCompletedAppointmentLocation.setVerifyInputWhenFocusTarget(false);
        pManageFeedback.add(tfCompletedAppointmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 190, 40));

        tfCompletedAppointmentStartTime.setEditable(false);
        tfCompletedAppointmentStartTime.setEnabled(false);
        tfCompletedAppointmentStartTime.setFocusable(false);
        tfCompletedAppointmentStartTime.setRequestFocusEnabled(false);
        tfCompletedAppointmentStartTime.setVerifyInputWhenFocusTarget(false);
        pManageFeedback.add(tfCompletedAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 190, 40));

        tfCompletedAppointmentEndTime.setEditable(false);
        tfCompletedAppointmentEndTime.setEnabled(false);
        tfCompletedAppointmentEndTime.setFocusable(false);
        tfCompletedAppointmentEndTime.setRequestFocusEnabled(false);
        tfCompletedAppointmentEndTime.setVerifyInputWhenFocusTarget(false);
        pManageFeedback.add(tfCompletedAppointmentEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 190, 40));

        taTechnicianFeedback.setColumns(20);
        taTechnicianFeedback.setRows(5);
        jScrollPane4.setViewportView(taTechnicianFeedback);

        pManageFeedback.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 290, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("APPOINTMENT ID");
        pManageFeedback.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, 30));

        lCompletedAppointmentLocation.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lCompletedAppointmentLocation.setText("APPOINTMENT LOCATION");
        pManageFeedback.add(lCompletedAppointmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 30));

        lCompletedAppointmentStartTime.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lCompletedAppointmentStartTime.setText("APPOINTMENT START TIME");
        pManageFeedback.add(lCompletedAppointmentStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 190, 30));

        lCompletedAppointmentEndTime.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lCompletedAppointmentEndTime.setText("APPOINTMENT END TIME");
        pManageFeedback.add(lCompletedAppointmentEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 180, 30));

        lTechnicianFeedback.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lTechnicianFeedback.setText("TECHNICIAN FEEDBACK");
        pManageFeedback.add(lTechnicianFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, 30));

        bSubmitFeedback.setBackground(new java.awt.Color(102, 255, 153));
        bSubmitFeedback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSubmitFeedback.setText("SUBMIT FEEDBACK");
        bSubmitFeedback.addActionListener(this::bSubmitFeedbackActionPerformed);
        pManageFeedback.add(bSubmitFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 140, 50));

        tpTabs.addTab("Manage Feedback", pManageFeedback);

        pProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfCurrentID.setEditable(false);
        tfCurrentID.setEnabled(false);
        tfCurrentID.setFocusable(false);
        tfCurrentID.setRequestFocusEnabled(false);
        tfCurrentID.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 41));

        tfCurrentRole.setEditable(false);
        tfCurrentRole.setEnabled(false);
        tfCurrentRole.setFocusable(false);
        tfCurrentRole.setRequestFocusEnabled(false);
        tfCurrentRole.setVerifyInputWhenFocusTarget(false);
        pProfile.add(tfCurrentRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 190, 41));
        pProfile.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 41));
        pProfile.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 190, 40));
        pProfile.add(tfCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, 30));

        lID.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lID.setText("USER ID");
        pProfile.add(lID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        lRole.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lRole.setText("USER ROLE");
        pProfile.add(lRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 20));

        lUsername.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lUsername.setText("NEW USERNAME");
        pProfile.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        lPassword.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lPassword.setText("NEW PASSWORD");
        lPassword.setToolTipText("");
        pProfile.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 20));

        lCurrentPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCurrentPassword.setText("Enter Current Password");
        pProfile.add(lCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        bUpdateData.setBackground(new java.awt.Color(102, 255, 153));
        bUpdateData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUpdateData.setText("UPDATE DATA");
        bUpdateData.addActionListener(this::bUpdateDataActionPerformed);
        pProfile.add(bUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 130, 50));

        tpTabs.addTab("Manage Profile", pProfile);

        getContentPane().add(tpTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 750, 500));

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OODJ Technician Screen.png"))); // NOI18N
        getContentPane().add(lBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.show();
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateDataActionPerformed
        String newUsername = tfUsername.getText();
        String newPassword = tfPassword.getText();
        String currentPassword = tfCurrentPassword.getText();

        try {
            bUpdateData.setEnabled(false);
            User user = loadCurrentUser();

            if(currentPassword.equals(user.getPassword())) {
                user.setUsername(newUsername);
                user.setPassword(newPassword);

                user.toString();

                FileHandler fh = new FileHandler("user.txt");
                fh.updateRecord(tfCurrentID.getText().trim(), user.toString());

                FileHandler fh2 = new FileHandler("login.txt");
                fh2.writeLoginUserRecord(user);
                
                JOptionPane.showMessageDialog(null, "Successfully updated User Profile!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);

                tfUsername.setText(newUsername);
                tfPassword.setText(newPassword);
                tfCurrentPassword.setText("");
                lUser.setText(newUsername);

            } else {
                JOptionPane.showMessageDialog(null, "Current Password is Incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            System.getLogger(CounterStaffScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
            bUpdateData.setEnabled(true);
        }
    }//GEN-LAST:event_bUpdateDataActionPerformed

    private void bCompleteAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompleteAppointmentActionPerformed
        String appointmentID = tfAppointmentID.getText();
        
        if (appointmentID.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please select Appointment!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        FileHandler fh = new FileHandler("appointment.txt");
        
        Appointment appointment = dh.getAppointmentByID(appointmentID);
        
        try {
            appointment.setAppointmentStatus("COMPLETED");
            fh.updateRecord(appointmentID, appointment.toString());
            
            tfAppointmentID.setText("");
            tfAppointmentLocation.setText("");
            tfAppointmentType.setText("");
            tfAppointmentStartTime.setText("");
            tfAppointmentEndTime.setText("");
                
            JOptionPane.showMessageDialog(null, "Appointment Completed", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            
            dh.loadUsers();
            dh.loadAppointments();
            loadAppointmentTable();
            loadCompletedAppointmentTable();
            
        } catch (IOException ex) {
            System.getLogger(TechnicianScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_bCompleteAppointmentActionPerformed

    private void bExportScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportScheduleActionPerformed
        
        FileHandler fh = new FileHandler("myAppointment.txt");

        int rowCount = tAppointments.getRowCount();
        
        try {
            fh.resetFile();
            for(int i = 0; i < rowCount; i++) {
         
                String appointmentID = tAppointments.getValueAt(i, 0).toString();
                Appointment appointment = dh.getAppointmentByID(appointmentID);
                
                if(appointment != null) {
                    fh.writeRecord(appointment);
                }
            }
            eh.appointmentTxtToExcel("myAppointment.txt");
            JOptionPane.showMessageDialog(null, "Schedule Exported Successfully!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.getLogger(TechnicianScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bExportScheduleActionPerformed

    private void bSubmitFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitFeedbackActionPerformed
        String technicianFeedback = taTechnicianFeedback.getText();
        String appointmentID = tfCompletedAppointmentID.getText();
        
        FileHandler fh = new FileHandler("appointment.txt");
        FileHandler fh2 = new FileHandler("feedback.txt");
        
        if (appointmentID.isBlank()) {
            JOptionPane.showMessageDialog(null, "Select Appointment First!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (technicianFeedback.isBlank()) {
            JOptionPane.showMessageDialog(null, "Technician Feedback is Empty!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Technician technician = (Technician) loadCurrentUser();
            Appointment appointment = dh.getAppointmentByID(appointmentID);
            Feedback feedback = dh.getFeedbackByAppointmentID(appointmentID);
        
            appointment.setAppointmentStatus("CLOSED");
        
            feedback.setTechnicianFeedback(technicianFeedback);
            feedback.setTechnician(technician);
            
            fh.updateRecord(appointmentID, appointment.toString());
            fh2.updateRecord(feedback.getFeedbackID(), feedback.toString());
            
            dh.loadUsers();
            dh.loadAppointments();
            loadCompletedAppointmentTable();
            
            tfCompletedAppointmentID.setText("");
            tfCompletedAppointmentLocation.setText("");   
            tfCompletedAppointmentStartTime.setText("");
            tfCompletedAppointmentEndTime.setText("");
            taTechnicianFeedback.setText("");
            
            JOptionPane.showMessageDialog(null, "Feedbcak Updated Successfully!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.getLogger(TechnicianScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bSubmitFeedbackActionPerformed
    
    private User loadCurrentUser() throws FileNotFoundException, IOException {
        String currentUserID = null;
        
        try(BufferedReader br = new BufferedReader(new FileReader("login.txt"))){
            String line = br.readLine();
            
            if(line != null) {
                String [] records = line.split("\\|");
                currentUserID = records [0].trim();      
            }
            
            return dh.getUserByID(currentUserID);
        }
    }
    
    private void loadAppointmentTable() throws IOException {
        Appointment [] appointments = dh.getAppointmentByStatus("ASSIGNED");
        
        DefaultTableModel model = (DefaultTableModel) tAppointments.getModel();
        model.setRowCount(0);
        
        String technicianID = loadCurrentUser().getUserID();
        
        for (Appointment a : appointments) {
            
            if (a == null) continue;
            
            if (a.getTechnician() == null) continue;

            if (!a.getTechnician().getUserID().equalsIgnoreCase(technicianID)) continue;
            
            model.addRow(new Object[] {
                a.getAppointmentID(),
                a.getAppointmentDate(),
                a.getCustomer().getUsername(),
                "Select"
            });
        }
    }
    
    private void loadCompletedAppointmentTable() throws IOException {
        Appointment [] appointments = dh.getAppointmentByStatus("COMPLETED");
        
        DefaultTableModel model = (DefaultTableModel) tCompletedAppointments.getModel();
        model.setRowCount(0);
        
        String technicianID = loadCurrentUser().getUserID();
        
        for (Appointment a : appointments) {
            
            if (a == null) continue;
            
            if (a.getTechnician() == null) continue;

            if (!a.getTechnician().getUserID().equalsIgnoreCase(technicianID)) continue;
            
            model.addRow(new Object[] {
                a.getAppointmentID(),
                a.getAppointmentDate(),
                a.getCustomer().getUsername(),
                "Select"
            });
        }
    }
    
    private void onStart() throws FileNotFoundException, IOException{
        
        dh.loadUsers();
        dh.loadAppointments();
        dh.loadFeedback();
        User user = loadCurrentUser();
         
        String username = user.getUsername();
        String password = user.getPassword();
        String role = user.getUserRole();
        String id = user.getUserID();
        
        lUser.setText(username);
        tfCurrentID.setText(id);
        tfCurrentRole.setText(role);
        tfUsername.setText(username);
        tfPassword.setText(password);
        loadAppointmentTable();
        loadCompletedAppointmentTable();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TechnicianScreen().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(TechnicianScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }
    
    class ButtonRenderer extends JButton implements TableCellRenderer {
        

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "" : value.toString());
            return this;
        }
        
    }
    
    class AppointmentSelectButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private Appointment appointment;
        private LocalTime time;
        private Feedback feedback;
        
        public AppointmentSelectButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Select");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String appointmentID = table.getValueAt(row, 0).toString(); 
                
                appointment = dh.getAppointmentByID(appointmentID);
                
                tfAppointmentID.setText(appointmentID);
                tfAppointmentLocation.setText(appointment.getAppointmentLocation());
                tfAppointmentType.setText(appointment.getAppointmentType());
                
                tfAppointmentStartTime.setText(appointment.getAppointmentStartTime().format(DateTimeFormatter.ofPattern("HH:mm")));
                tfAppointmentEndTime.setText(appointment.getAppointmentEndTime().format(DateTimeFormatter.ofPattern("HH:mm")));
                
                feedback = dh.getFeedbackByAppointmentID(appointmentID);
                
                taCustomerFeedback.setText(feedback.getCustomerFeedback());

            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Select";
        }
    }
    
    class CompletedAppointmentSelectButtonEditor extends DefaultCellEditor {
        
        private JButton button;
        private JTable table;
        private Appointment appointment;
        private LocalTime time;
        private Feedback feedback;
        
        public CompletedAppointmentSelectButtonEditor(JCheckBox checkBox, JTable table) {
            
            super(checkBox);
            this.table = table;
            
            button = new JButton("Select");
            
            button.addActionListener(e -> {
                
                fireEditingStopped();
                
                int row = table.getSelectedRow();
                
                if (row < 0) return;
                
                String appointmentID = table.getValueAt(row, 0).toString(); 
                
                appointment = dh.getAppointmentByID(appointmentID);
                
                tfCompletedAppointmentID.setText(appointmentID);
                tfCompletedAppointmentLocation.setText(appointment.getAppointmentLocation());   
                tfCompletedAppointmentStartTime.setText(appointment.getAppointmentStartTime().format(DateTimeFormatter.ofPattern("HH:mm")));
                tfCompletedAppointmentEndTime.setText(appointment.getAppointmentEndTime().format(DateTimeFormatter.ofPattern("HH:mm")));
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
                return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Select";
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCompleteAppointment;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bExportSchedule;
    private javax.swing.JButton bSubmitFeedback;
    private javax.swing.JButton bUpdateData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lAppointmentEndTime;
    private javax.swing.JLabel lAppointmentID;
    private javax.swing.JLabel lAppointmentLocation;
    private javax.swing.JLabel lAppointmentStartTime;
    private javax.swing.JLabel lAppointmentType;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lCompletedAppointmentEndTime;
    private javax.swing.JLabel lCompletedAppointmentLocation;
    private javax.swing.JLabel lCompletedAppointmentStartTime;
    private javax.swing.JLabel lCurrentPassword;
    private javax.swing.JLabel lCustomerComment;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lRole;
    private javax.swing.JLabel lTechnicianFeedback;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel pManageAppointments;
    private javax.swing.JPanel pManageFeedback;
    private javax.swing.JPanel pProfile;
    private javax.swing.JTable tAppointments;
    private javax.swing.JTable tCompletedAppointments;
    private javax.swing.JTextArea taCustomerFeedback;
    private javax.swing.JTextArea taTechnicianFeedback;
    private javax.swing.JTextField tfAppointmentEndTime;
    private javax.swing.JTextField tfAppointmentID;
    private javax.swing.JTextField tfAppointmentLocation;
    private javax.swing.JTextField tfAppointmentStartTime;
    private javax.swing.JTextField tfAppointmentType;
    private javax.swing.JTextField tfCompletedAppointmentEndTime;
    private javax.swing.JTextField tfCompletedAppointmentID;
    private javax.swing.JTextField tfCompletedAppointmentLocation;
    private javax.swing.JTextField tfCompletedAppointmentStartTime;
    private javax.swing.JTextField tfCurrentID;
    private javax.swing.JPasswordField tfCurrentPassword;
    private javax.swing.JTextField tfCurrentRole;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTabbedPane tpTabs;
    // End of variables declaration//GEN-END:variables
}
